// English educational copy; Portuguese source strings are stable translation keys.
export const enContent: Record<string,string> = {
  "O registro não conta toda a história": "Documentation does not tell the whole story",
  "Na UTI oncológica, os registros sugerem adesão desigual entre os turnos. A direção quer um novo treinamento; os profissionais apontam duplicidade no prontuário. Ainda não sabemos quanto da lacuna é de documentação e quanto é de execução.": "In the oncology ICU, documentation suggests uneven adherence across shifts. Management wants more training; staff report duplicate charting. We do not yet know how much of the gap concerns documentation and how much concerns delivery of care.",
  "Distinguir lacuna de registro e lacuna de execução": "Distinguish documentation gaps from delivery gaps",
  "Priorizar determinantes do fluxo e dos turnos": "Prioritize determinants related to workflow and shifts",
  "Planejar um piloto e acompanhar alcance e fidelidade": "Plan a pilot and monitor reach and fidelity",
  "Registro · diurno": "Documentation · day shift",
  "52/60": "52/60",
  "Oportunidades elegíveis com avaliação de risco documentada": "Eligible opportunities with a documented risk assessment",
  "Registro · noturno": "Documentation · night shift",
  "18/40": "18/40",
  "Mesmo critério, em oportunidades elegíveis do turno noturno": "The same criterion, applied to eligible night-shift opportunities",
  "Observação direta": "Direct observation",
  "16/30": "16/30",
  "Oportunidades observadas com todos os componentes essenciais executados": "Observed opportunities in which all core components were delivered",
  "Treinamento": "Training",
  "28/32": "28/32",
  "Profissionais elegíveis que participaram; isso não comprova execução": "Eligible staff who attended; attendance does not establish delivery",
  "Enfermeira do diurno": "Day-shift nurse",
  "Eu registro o risco na evolução e novamente no formulário. Há colegas que fazem o cuidado, mas deixam uma das telas vazia.": "I record the risk in the progress note and again in the form. Some colleagues provide the care but leave one screen blank.",
  "A documentação pode subestimar parte da execução; investigar antes de atribuir a lacuna ao conhecimento.": "Documentation may underestimate some delivery; investigate before attributing the gap to knowledge.",
  "Técnico do noturno": "Night-shift nursing technician",
  "O formulário só abre no computador do posto. Durante os cuidados, anotamos em papel. A reunião de adaptação sempre acontece de manhã.": "The form only opens on the nursing-station computer. During care, we write on paper. The adaptation meeting always takes place in the morning.",
  "Acesso ao sistema e participação do noturno são condições do contexto e dos destinatários.": "System access and night-shift participation are conditions affecting the context and recipients.",
  "Registro escrito da auditora": "Auditor's written note",
  "Na observação direta também faltaram componentes essenciais. Simplificar o registro pode ajudar, mas não podemos presumir que resolverá o cuidado.": "Direct observation also showed missing core components. Simplifying documentation may help, but we cannot assume it will solve care delivery.",
  "Há indícios de duas lacunas: documentação e execução. Uma mudança de sistema precisa de medidas distintas.": "There is evidence of two gaps: documentation and delivery. A system change requires distinct measures.",
  "A TI só poderá alterar o prontuário daqui a seis semanas. O noturno pede uma solução provisória sem um terceiro registro.": "IT will only be able to change the charting system in six weeks. The night shift requests an interim solution without a third record.",
  "Escolher a lacuna e o primeiro teste": "Choose the gap and the first test",
  "A direção oferece apoio para um piloto de duas semanas. Definam o que será investigado antes de expandir o projeto.": "Management offers support for a two-week pilot. Define what you will investigate before expanding the project.",
  "Como iniciar a ação sem confundir ausência de registro com ausência de cuidado?": "How can action begin without equating missing documentation with missing care?",
  "Que lacuna será investigada e com quais fontes?": "Which gap will you investigate, and with which sources?",
  "Como incluir os dois turnos e adaptar o conhecimento ao fluxo local?": "How will you include both shifts and adapt knowledge to local workflow?",
  "Mapear registro e execução nos dois turnos": "Map documentation and delivery across both shifts",
  "Observar o processo e testar uma adaptação em pequena escala, comparando registro e execução.": "Observe the process and test a small-scale adaptation, comparing documentation with delivery.",
  "O piloto produz evidências úteis para adaptar a prática, mas exige tempo para observação e escuta. Definam quem participa e como evitar avaliar apenas o diurno.": "The pilot provides useful evidence for adapting practice but requires time for observation and listening. Define who participates and how to avoid evaluating only the day shift.",
  "Começar pelo noturno e ampliar depois": "Start with the night shift and expand later",
  "Concentrar inicialmente a investigação no turno com menor documentação.": "Initially focus the investigation on the shift with less documentation.",
  "A prioridade atende uma lacuna visível. Porém, a documentação não descreve toda a execução; comparem fontes e explicitem o critério para ampliar o piloto ao diurno.": "This priority addresses a visible gap. However, documentation does not describe all delivery; compare sources and specify the criterion for extending the pilot to the day shift.",
  "Oferecer capacitação prática antes do piloto": "Offer practical training before the pilot",
  "Realizar demonstração dos componentes essenciais e depois observar sua execução.": "Demonstrate the core components and then observe their delivery.",
  "A demonstração pode enfrentar uma necessidade de habilidade. Ainda falta confirmar essa barreira e lidar com duplicidade e acesso ao registro; evitem atribuir toda a lacuna à capacitação.": "The demonstration may address a skills need. You still need to confirm this barrier and address duplication and chart access; avoid attributing the entire gap to training.",
  "Confrontar as pistas do processo": "Compare the workflow clues",
  "Conversem com Helena no posto e André na sala da equipe; leiam a nota de Beatriz no núcleo de qualidade. As fontes descrevem explicações diferentes para a mesma taxa de registro.": "Speak with Helena at the nursing station and André in the staff room; read Beatriz's note in the quality office. These sources offer different explanations for the same documentation rate.",
  "Que determinantes devem orientar a estratégia e qual hipótese ainda precisa ser verificada?": "Which determinants should guide the strategy, and which hypothesis still needs checking?",
  "Relacionem duas pistas aos determinantes do CFIR e expliquem como se articulam.": "Relate two clues to CFIR determinants and explain how they interact.",
  "Qual evidência confirmaria ou enfraqueceria a hipótese prioritária?": "What evidence would support or weaken the priority hypothesis?",
  "Priorizar fluxo do registro e participação dos turnos": "Prioritize documentation workflow and shift participation",
  "Mapear tarefas, acesso ao prontuário e participação do noturno antes de selecionar a adaptação.": "Map tasks, chart access and night-shift participation before selecting an adaptation.",
  "A estratégia dialoga com os relatos, mas a auditoria mostra execução incompleta. Expliquem como uma medida de cuidado acompanhará a mudança de registro.": "The strategy addresses the accounts, but the audit shows incomplete delivery. Explain how a care-delivery measure will accompany the documentation change.",
  "Priorizar conhecimentos e habilidades da equipe": "Prioritize staff knowledge and skills",
  "Investigar entendimento e execução dos componentes essenciais com observação e conversa.": "Investigate understanding and delivery of core components through observation and conversation.",
  "Pode existir uma necessidade de aprendizagem. Os dados de treinamento não comprovam competência, e as dificuldades do sistema continuam relevantes; expliquem como separar esses determinantes.": "There may be a learning need. Training data do not establish competence, and system difficulties remain relevant; explain how to distinguish these determinants.",
  "Priorizar pactuação de responsabilidades": "Prioritize agreed responsibilities",
  "Definir quem avalia, executa e confere cada componente na passagem do plantão.": "Define who assesses, delivers and checks each component during shift handover.",
  "Responsabilidades claras podem apoiar a execução. Se a tela continuar inacessível e o noturno não participar, a pactuação pode virar apenas uma cobrança; descrevam as condições necessárias.": "Clear responsibilities may support delivery. If the screen remains inaccessible and the night shift is excluded, the agreement may become merely an additional demand; describe the conditions needed.",
  "Facilitar sem criar mais trabalho": "Facilitate without adding more work",
  "A facilitadora dispõe de dois encontros curtos por semana. A mudança do sistema depende da TI e não ocorrerá durante o piloto.": "The facilitator has time for two short meetings each week. The system change depends on IT and will not happen during the pilot.",
  "Como articular inovação, destinatários e contexto diante dessa limitação?": "How can innovation, recipients and context be aligned under this constraint?",
  "Que ação a facilitadora realizará com o noturno e a TI?": "What will the facilitator do with the night shift and IT?",
  "O que pode ser adaptado agora, preservando os componentes essenciais?": "What can be adapted now while preserving core components?",
  "Cocriar um fluxo provisório entre os turnos": "Co-design an interim workflow across shifts",
  "Reunir representantes dos dois turnos, eliminar duplicidade autorizada e testar a organização do cuidado.": "Bring together representatives from both shifts, remove authorized duplication and test the organization of care.",
  "O apoio considera os destinatários e o contexto. Confirmem com a instituição quais registros podem ser ajustados; uma solução provisória não deve gerar nova duplicidade.": "The support considers recipients and context. Confirm with the institution which records may be changed; an interim solution should not create further duplication.",
  "Aguardar a TI e preparar a mudança": "Wait for IT and prepare the change",
  "Usar o período para mapear necessidades, combinar responsabilidades e preparar um piloto do novo registro.": "Use this period to map needs, agree responsibilities and prepare a pilot of the new documentation process.",
  "Evita implantar uma solução temporária que será abandonada. A lacuna de cuidado pode persistir por seis semanas; defendam como será acompanhada durante a espera.": "This avoids introducing a temporary solution that will be abandoned. The care gap may persist for six weeks; explain how it will be monitored during the wait.",
  "Começar com acompanhamento na passagem do plantão": "Start with support during shift handover",
  "A facilitadora acompanha o processo e dá devolutivas breves sobre os componentes essenciais.": "The facilitator follows the process and provides brief feedback on the core components.",
  "Oferece apoio imediato, mas depende do tempo e da presença da facilitadora. Planejem como o acompanhamento se distribuirá entre os turnos e continuará depois do piloto.": "This offers immediate support but depends on the facilitator's time and presence. Plan how support will cover both shifts and continue after the pilot.",
  "Construir um painel que não esconda o noturno": "Build a dashboard that does not hide the night shift",
  "No piloto, 18 de 24 pacientes elegíveis receberam a prática. Foram 14 de 16 no diurno e 4 de 8 no noturno. Os dados são de pacientes distintos, atribuídos ao turno de sua primeira oportunidade no piloto.": "In the pilot, 18 of 24 eligible patients received the practice: 14 of 16 on the day shift and 4 of 8 on the night shift. These are distinct patients, assigned to the shift of their first eligible opportunity in the pilot.",
  "Que avaliação RE-AIM informa alcance e representatividade sem concluir eficácia a partir desses números?": "Which RE-AIM assessment informs reach and representativeness without inferring effectiveness from these numbers?",
  "Definam numerador, denominador, fonte e momento para um indicador.": "Define the numerator, denominator, source and time point for an indicator.",
  "Que comparação é necessária para não esconder a diferença entre os turnos?": "Which comparison is needed to make the difference between shifts visible?",
  "Mostrar alcance geral e por turno": "Show overall reach and reach by shift",
  "Apresentar 18/24 no total, 14/16 no diurno e 4/8 no noturno, com perfil dos pacientes.": "Report 18/24 overall, 14/16 for the day shift and 4/8 for the night shift, together with patient characteristics.",
  "O alcance global é 75%, mas esconde uma diferença entre 87,5% e 50%. Verifiquem perfis e oportunidades antes de atribuir a diferença ao turno.": "Overall reach is 75%, but it hides a difference between 87.5% and 50%. Examine patient characteristics and opportunities before attributing the difference to the shift.",
  "Começar com alcance global e análise das perdas": "Start with overall reach and analysis of those not reached",
  "Usar 18/24 e investigar os seis pacientes não alcançados.": "Use 18/24 and investigate the six patients who were not reached.",
  "A investigação das perdas pode identificar exclusões importantes. O total sozinho não mostra sua distribuição; indiquem como os turnos e os perfis serão examinados.": "Investigating those not reached may reveal important exclusions. The total alone does not show their distribution; specify how shifts and patient characteristics will be examined.",
  "Priorizar execução dos componentes no piloto": "Prioritize delivery of the components in the pilot",
  "Auditar componentes essenciais e adaptações, complementando a avaliação de implementação do RE-AIM.": "Audit core components and adaptations to complement RE-AIM's implementation assessment.",
  "A execução é relevante, mas responde a uma dimensão diferente do alcance. Indiquem como saberão quem recebeu a prática e quem ficou de fora.": "Delivery is relevant, but it addresses a different dimension from reach. Explain how you will establish who received the practice and who was left out.",
  "Defender fidelidade sem confundi-la com registro": "Defend fidelity without equating it with documentation",
  "O registro aumentou após o piloto. A direção quer declarar que o protocolo já foi incorporado. Sua equipe precisa defender como essa afirmação será investigada.": "Documentation increased after the pilot. Management wants to declare that the protocol is embedded in practice. Your team must explain how that claim will be investigated.",
  "Qual desfecho de implementação será prioritário e qual conclusão os dados ainda não permitem?": "Which implementation outcome will be prioritized, and which conclusion is not yet supported by the data?",
  "Definam uma medida de fidelidade, incluindo componentes essenciais, fonte e periodicidade.": "Define a fidelity measure, including core components, source and frequency.",
  "Que adaptação é aceitável e que mudança descaracterizaria a prática?": "Which adaptation is acceptable, and which change would undermine the practice's core components?",
  "Combinar observação e auditoria de fidelidade": "Combine observation with a fidelity audit",
  "Medir oportunidades com componentes essenciais executados / oportunidades elegíveis, conciliando fontes.": "Measure opportunities with core components delivered / eligible opportunities, reconciling sources.",
  "A proposta distingue documentação de execução. Expliquem como selecionar oportunidades, lidar com divergências entre fontes e acompanhar os dois turnos.": "This proposal distinguishes documentation from delivery. Explain how to select opportunities, address disagreements between sources and monitor both shifts.",
  "Usar o registro como sinal inicial de fidelidade": "Use documentation as an initial signal of fidelity",
  "Acompanhar a documentação e validar uma amostra por observação direta.": "Monitor documentation and validate a sample through direct observation.",
  "Pode reduzir o esforço da avaliação. O registro só poderá representar a execução se essa relação for examinada; explicitem a amostra e os limites da conclusão.": "This may reduce assessment effort. Documentation can only represent delivery if that relationship is examined; specify the sample and limits of the conclusion.",
  "Investigar viabilidade antes de ampliar o piloto": "Investigate feasibility before expanding the pilot",
  "Examinar tempo, acesso ao sistema e condições para executar os componentes essenciais.": "Examine time, system access and the conditions required to deliver core components.",
  "A viabilidade pode orientar a expansão. Ela não comprova fidelidade; incluam uma medida complementar de execução e justifiquem a ordem das avaliações.": "Feasibility may guide expansion. It does not establish fidelity; include a complementary delivery measure and justify the sequence of assessments.",
  "A equipe distinguiu registro de execução?": "Did the team distinguish documentation from delivery?",
  "A estratégia incluiu os dois turnos e preservou componentes essenciais?": "Did the strategy include both shifts and preserve core components?",
  "O indicador permite investigar fidelidade sem inferir causalidade clínica?": "Does the indicator investigate fidelity without inferring clinical causality?",
  "A prática depende de um abastecimento viável": "Practice depends on feasible supply arrangements",
  "Na clínica cirúrgica, duas de quatro equipes elegíveis iniciaram o protocolo. O abastecimento é irregular e buscar materiais consome tempo. Um estoque maior resolve parte do problema, mas pode aumentar perdas e custos.": "In the surgical ward, two of four eligible care teams started the protocol. Supply is irregular, and collecting materials takes time. Larger stock resolves part of the problem but may increase waste and costs.",
  "Distinguir início de adoção e execução cotidiana": "Distinguish initial adoption from day-to-day delivery",
  "Negociar uma estratégia compatível com recursos e fluxo": "Negotiate a strategy compatible with resources and workflow",
  "Avaliar adoção, viabilidade e custo de implementação": "Assess adoption, feasibility and implementation cost",
  "Equipes que iniciaram": "Teams that started",
  "2/4": "2/4",
  "Equipes elegíveis; início de uso, não execução contínua": "Eligible teams; initial use, rather than sustained delivery",
  "Abastecimento incompleto": "Incomplete supply",
  "3/10 dias": "3/10 days",
  "Dias do período observado com falta de pelo menos um material previsto": "Days in the observation period when at least one required material was missing",
  "Busca de material": "Collecting materials",
  "14 min": "14 min",
  "Mediana de tempo por busca nas 12 buscas acompanhadas": "Median time per collection across the 12 observed collections",
  "Custo adicional do piloto": "Additional pilot cost",
  "R$ 480": "R$ 480",
  "Estimativa fictícia inicial; ainda sem tempo de trabalho e desperdício": "Initial fictional estimate; staff time and waste are not yet included",
  "Registro de consumo e reposição": "Consumption and replenishment record",
  "O consumo varia por cirurgia e ocupação. Um estoque fixo sem reposição pode faltar em um dia e vencer em outro.": "Consumption varies with surgery and occupancy. Fixed stock without replenishment may run out one day and expire another.",
  "O fluxo de reposição e a variação da demanda precisam compor a estratégia, além da quantidade em estoque.": "The replenishment process and variation in demand must inform the strategy, alongside stock quantity.",
  "Responsável pela unidade": "Ward lead",
  "Duas equipes começaram, mas não reservei tempo para conferir os materiais. Na alta demanda, o problema volta.": "Two teams started, but I did not reserve time to check materials. During high demand, the problem returns.",
  "O início da adoção não assegura condições de execução; apoio organizacional e responsabilidades são relevantes.": "Initial adoption does not ensure delivery conditions; organizational support and responsibilities matter.",
  "Plantão noturno cirúrgico": "Surgical night shift",
  "O estoque é conferido de manhã. Se falta à noite, a autorização demora e saímos da unidade para buscar.": "Stock is checked in the morning. If something is missing at night, authorization takes time and we leave the ward to collect it.",
  "A estratégia precisa considerar reposição e acesso durante a noite, não apenas o horário de conferência.": "The strategy needs to address replenishment and access at night, rather than only the stock-checking schedule.",
  "A instituição não aprovará contratação adicional neste mês. O orçamento do piloto permanece R$ 480 e deve incluir desperdício e tempo de trabalho.": "The institution will not approve additional hiring this month. The pilot budget remains R$ 480 and must include waste and staff time.",
  "Definir o problema além da falta de material": "Define the problem beyond missing materials",
  "A direção oferece um piloto em uma equipe cirúrgica. A adoção inicial foi de 2/4 equipes, mas o abastecimento varia durante a semana.": "Management offers a pilot in one surgical care team. Initial adoption was 2/4 teams, but supply varies throughout the week.",
  "Que problema de implementação deve orientar o piloto e o que precisa ser adaptado?": "Which implementation problem should guide the pilot, and what needs adaptation?",
  "Qual lacuna será priorizada: início de uso, execução ou condições de abastecimento?": "Which gap will be prioritized: initial use, delivery or supply conditions?",
  "Que dados e participantes orientarão a adaptação ao contexto?": "Which data and participants will guide contextual adaptation?",
  "Mapear demanda e reposição antes de aumentar o estoque": "Map demand and replenishment before increasing stock",
  "Investigar consumo, falta, tempo de busca e responsabilidades ao longo dos turnos.": "Investigate consumption, shortages, collection time and responsibilities across shifts.",
  "Permite adaptar a estratégia à demanda real. A investigação precisa ter prazo e uma resposta provisória para as faltas durante o piloto.": "This allows the strategy to respond to actual demand. The investigation needs a deadline and an interim response to shortages during the pilot.",
  "Testar um estoque local limitado": "Test limited local stock",
  "Criar uma pequena reserva na equipe piloto e acompanhar consumo, faltas e perdas.": "Create a small reserve for the pilot team and monitor consumption, shortages and waste.",
  "Pode reduzir deslocamentos rapidamente. Sem regra de reposição e controle de perdas, a reserva pode apenas deslocar o problema; definam critérios do teste.": "This may quickly reduce travel. Without replenishment rules and waste control, the reserve may simply move the problem elsewhere; define test criteria.",
  "Começar com as duas equipes que ainda não adotaram": "Start with the two teams that have not yet adopted",
  "Investigar por que não iniciaram a prática antes de ampliar a oferta de materiais.": "Investigate why they did not start the practice before increasing material availability.",
  "A pergunta sobre adoção é pertinente. Não presumam que as duas equipes que começaram já conseguem executar; comparem suas condições de trabalho.": "The adoption question is relevant. Do not assume the two teams that started can already deliver the practice; compare their working conditions.",
  "Separar barreira de estratégia": "Distinguish a barrier from a strategy",
  "Conversem com Lia e Joana na sala da equipe e consultem o relatório de Paulo no almoxarifado. Comparem problemas de demanda, gestão e acesso antes de priorizar.": "Speak with Lia and Joana in the staff room and consult Paulo's report in the supply room. Compare demand, management and access problems before setting priorities.",
  "Como organizar os determinantes sem tratar “criar estoque” como se fosse uma barreira?": "How can determinants be organized without treating ‘creating stock’ as a barrier?",
  "Identifiquem dois determinantes do CFIR sustentados pelos relatos.": "Identify two CFIR determinants supported by the accounts.",
  "Qual estratégia responde a cada determinante e qual risco pode permanecer?": "Which strategy addresses each determinant, and which risk may remain?",
  "Priorizar acesso aos recursos e fluxo de reposição": "Prioritize access to resources and replenishment workflow",
  "Relacionar faltas e tempo de busca à disponibilidade de recursos e às condições do processo.": "Relate shortages and collection time to resource availability and process conditions.",
  "Há sustentação nos relatos. O apoio da liderança e a pactuação de responsabilidades também precisam entrar no plano para que a reposição aconteça.": "The accounts support this priority. Leadership support and agreed responsibilities also need to be included so replenishment actually happens.",
  "Priorizar apoio organizacional e responsabilidades": "Prioritize organizational support and responsibilities",
  "Negociar quem acompanha o abastecimento e como as decisões serão tomadas.": "Negotiate who monitors supply and how decisions will be made.",
  "Pode enfrentar a falta de tempo e de responsabilidade definida. Uma pactuação sem conhecer consumo e acesso no noturno pode continuar produzindo faltas.": "This may address lack of time and unclear responsibility. An agreement that ignores consumption and night-shift access may still produce shortages.",
  "Priorizar a compatibilidade com os turnos": "Prioritize compatibility across shifts",
  "Revisar horários de conferência e autorização em função do trabalho noturno.": "Review checking and authorization times in relation to night-shift work.",
  "Enfrenta uma desigualdade do fluxo. Expliquem como a adaptação se integra ao abastecimento global, sem multiplicar estoques e perdas.": "This addresses an unequal workflow. Explain how the adaptation fits the overall supply process without multiplying stocks and waste.",
  "Negociar uma solução dentro do orçamento": "Negotiate a solution within the budget",
  "O apoio financeiro inicial é limitado. A facilitadora pode articular a unidade e o abastecimento, mas não decide compras ou mudanças institucionais sozinha.": "Initial funding is limited. The facilitator can connect the ward with supply staff but cannot independently decide purchases or institutional changes.",
  "Como tornar a prática executável sem uma solução dependente apenas de esforço individual?": "How can practice become feasible without relying solely on individual effort?",
  "Que negociação a facilitadora fará com os destinatários e a liderança?": "What will the facilitator negotiate with recipients and leadership?",
  "Como lidar com reposição noturna, tempo e desperdício?": "How will night-time replenishment, staff time and waste be addressed?",
  "Reserva local com reposição por consumo e limite de perdas": "Local reserve with consumption-based replenishment and waste limits",
  "Pactuar quantidade mínima, rotina de conferência e acesso noturno na equipe piloto.": "Agree a minimum quantity, checking routine and night-time access for the pilot team.",
  "Pode equilibrar disponibilidade e perdas. Definam responsabilidades, regra de reposição e medida de custo; o estoque sozinho não é a facilitação.": "This may balance availability with waste. Define responsibilities, replenishment rules and a cost measure; stock alone is not facilitation.",
  "Distribuição programada por turno": "Scheduled distribution by shift",
  "Combinar entrega ao início dos turnos com um fluxo de contingência para demanda extra.": "Combine deliveries at the start of each shift with a contingency process for extra demand.",
  "Pode reduzir estoques dispersos. A demanda cirúrgica varia; a contingência precisa funcionar à noite e ter responsável definido.": "This may reduce scattered stocks. Surgical demand varies; the contingency process must work at night and have a designated responsible person.",
  "Manter estoque central com acesso simplificado": "Keep central stock with simpler access",
  "Negociar autorização e retirada rápidas, acompanhando o tempo de busca.": "Negotiate quick authorization and collection while monitoring collection time.",
  "Pode limitar desperdício local, mas deslocamentos permanecem. Defendam em que condições essa opção é viável e como o tempo será considerado.": "This may limit local waste, but travel remains. Explain under which conditions this option is feasible and how time will be accounted for.",
  "Avaliar adoção sem esconder execução e custos": "Assess adoption without hiding delivery and costs",
  "Após o piloto, três de quatro equipes elegíveis iniciaram o protocolo. Uma nova equipe ainda enfrenta faltas; foram gastos R$ 720, considerando materiais, tempo e perdas.": "After the pilot, three of four eligible teams started the protocol. One new team still faces shortages; expenditure was R$ 720, including materials, staff time and waste.",
  "Que dimensões do RE-AIM ajudam a avaliar o avanço e seus limites?": "Which RE-AIM dimensions help assess progress and its limits?",
  "Definam uma medida de adoção com numerador, denominador e fonte.": "Define an adoption measure with a numerator, denominator and source.",
  "Que informações de implementação e custo complementam essa medida?": "Which implementation and cost information complements this measure?",
  "Adoção das equipes junto de execução e custos": "Assess team adoption alongside delivery and costs",
  "Apresentar 3/4 equipes, examinar seus perfis e acompanhar faltas, componentes executados e custos.": "Report 3/4 teams, examine their characteristics and monitor shortages, delivered components and costs.",
  "A adoção passou a 75%; isso não comprova execução consistente. O custo real superou a estimativa inicial, cuja composição era incompleta; explicitem ambas as bases.": "Adoption reached 75%; this does not establish consistent delivery. Actual cost exceeded the initial estimate, whose composition was incomplete; specify the basis of each figure.",
  "Adoção com foco nas equipes que ficaram de fora": "Assess adoption with a focus on teams left out",
  "Apresentar 3/4 e investigar condições da quarta equipe para uma expansão posterior.": "Report 3/4 and investigate the fourth team's conditions for later expansion.",
  "A investigação das não adotantes informa representatividade e expansão. Acrescentem como avaliar a prática nas três que começaram e os recursos necessários.": "Investigating non-adopters informs representativeness and expansion. Add how you will assess practice in the three teams that started and the resources required.",
  "Avaliação detalhada da implementação no piloto": "Assess implementation in detail within the pilot",
  "Acompanhar faltas, adaptações, tempo e custo na equipe piloto antes de ampliar.": "Monitor shortages, adaptations, time and cost in the pilot team before expanding.",
  "Produz informações de execução, mas ainda não descreve adoção no conjunto do serviço. Expliquem como combinar o piloto com o panorama das quatro equipes.": "This provides delivery information but does not yet describe adoption across the service. Explain how to combine pilot findings with the picture across all four teams.",
  "Defender viabilidade e custo de implementação": "Defend feasibility and implementation cost",
  "A direção quer expandir com base no aumento de adoção. A equipe deve apresentar se a solução é executável e quais recursos exige.": "Management wants to expand based on increased adoption. The team must show whether the solution can be delivered and which resources it requires.",
  "Que desfechos permitem decidir sobre expansão sem equiparar adoção, viabilidade e resultado clínico?": "Which outcomes inform expansion without equating adoption, feasibility and clinical results?",
  "Descrevam como avaliar viabilidade: pessoas, fluxo, fonte e momento.": "Describe how to assess feasibility: people, workflow, source and time point.",
  "Quais componentes entrarão no custo de implementação e como serão separados dos custos assistenciais habituais?": "Which components belong in implementation cost, and how will they be separated from usual care costs?",
  "Triangular viabilidade com uma estimativa completa de custo": "Triangulate feasibility with a complete cost estimate",
  "Combinar relatos, observação do fluxo e registros de recursos usados especificamente na implementação.": "Combine accounts, workflow observation and records of resources used specifically for implementation.",
  "As fontes podem revelar dificuldades que a adoção não mostra. Definam período, perspectiva e quais custos são incrementais; não somem indistintamente toda a assistência.": "These sources may reveal difficulties that adoption does not show. Define the period, perspective and incremental costs; do not indiscriminately include all care costs.",
  "Testar a viabilidade em alta e baixa demanda": "Test feasibility during high and low demand",
  "Comparar tempo, faltas e execução em períodos distintos antes da expansão.": "Compare time, shortages and delivery across different periods before expansion.",
  "A variação da demanda é importante. A comparação não isola efeito causal e precisa considerar ocupação, perfil cirúrgico e recursos usados em cada período.": "Demand variation matters. The comparison does not isolate a causal effect and needs to consider occupancy, surgical case mix and resources used in each period.",
  "Expandir gradualmente com monitoramento de viabilidade": "Expand gradually while monitoring feasibility",
  "Incluir uma nova equipe por vez, mantendo critérios de revisão do fluxo e dos custos.": "Include one new team at a time, retaining criteria for reviewing workflow and costs.",
  "Permite aprender durante a expansão, mas expõe novas equipes a dificuldades do fluxo. Definam quando interromper, ajustar ou continuar a expansão.": "This allows learning during expansion but exposes new teams to workflow difficulties. Define when to stop, adjust or continue expansion.",
  "O plano distingue adoção inicial de execução?": "Does the plan distinguish initial adoption from delivery?",
  "A facilitação inclui liderança, abastecimento e noturno?": "Does facilitation include leadership, supply staff and the night shift?",
  "A avaliação de viabilidade e custo considera demanda, tempo e perdas?": "Does the feasibility and cost assessment consider demand, time and waste?",
  "A prática precisa sobreviver à saída da referência": "Practice must survive the practice lead’s departure",
  "Na internação, profissionais aprovam o protocolo, mas o uso depende de uma enfermeira de referência. Ela sairá da unidade em um mês. A rotatividade e a integração incompleta dos recém-admitidos ameaçam a continuidade.": "In the inpatient ward, staff approve of the protocol, but its use depends on a practice lead nurse. She will leave the ward in one month. Staff turnover and incomplete onboarding of new hires threaten continuity.",
  "Distinguir aceitabilidade, adoção e execução": "Distinguish acceptability, adoption and delivery",
  "Distribuir a facilitação e integrar recém-admitidos": "Distribute facilitation and include newly hired staff",
  "Planejar manutenção e avaliar sustentabilidade": "Plan maintenance and assess sustainability",
  "Aprovação do protocolo": "Protocol approval",
  "22/24": "22/24",
  "Respondentes que o consideraram aceitável; não é medida de uso": "Respondents who found it acceptable; this is not a measure of use",
  "Execução observada": "Observed delivery",
  "15/40": "15/40",
  "Oportunidades observadas com componentes essenciais executados": "Observed opportunities with core components delivered",
  "Integração dos novos": "New-staff onboarding",
  "6/12": "6/12",
  "Recém-admitidos elegíveis incluídos na apresentação e prática acompanhada": "Eligible newly hired staff included in the introduction and supported practice",
  "Saída da referência": "Practice lead's departure",
  "30 dias": "30 days",
  "Prazo para organizar continuidade antes da transferência da enfermeira": "Time available to organize continuity before the nurse transfers",
  "Recém-admitido": "Newly hired staff member",
  "Recebi o PDF na integração, mas nunca acompanhei o fluxo com alguém. Quando tenho dúvida, espero a enfermeira de referência chegar.": "I received the PDF during onboarding but never went through the workflow with someone. When I have questions, I wait for the practice lead to arrive.",
  "Aceitar a prática não elimina necessidades dos destinatários; a integração atual oferece informação, mas pouco apoio à execução.": "Accepting the practice does not remove recipients' needs; current onboarding provides information but little support for delivery.",
  "Referência que será transferida": "Practice lead awaiting transfer",
  "Eu cobro o registro e reorganizo os cuidados toda manhã. Ainda não combinamos quem fará isso quando eu sair.": "I check documentation and reorganize care every morning. We have not yet agreed who will do this after I leave.",
  "A continuidade está concentrada em uma pessoa, sem papel distribuído ou rotina organizacional definida.": "Continuity depends on one person, without distributed roles or a defined organizational routine.",
  "Registro da liderança noturna": "Written account from night-shift leadership",
  "Podemos assumir parte do apoio, mas precisamos de tempo e saber quais ajustes são permitidos. A integração dos novos ocorre só no diurno.": "We can provide some support, but we need time and clarity about permitted adjustments. New-staff onboarding only happens on the day shift.",
  "Há disponibilidade para facilitação distribuída, condicionada a apoio, preparação e inclusão dos turnos.": "There is willingness to share facilitation, provided there is support, preparation and inclusion of both shifts.",
  "Marta sairá uma semana antes do previsto. Chegarão quatro profissionais novos no próximo mês e não haverá aumento de carga horária.": "Marta will leave a week earlier than planned. Four new staff members will arrive next month, with no increase in allocated working hours.",
  "Planejar uma transição com propósito": "Plan a purposeful transition",
  "Há um mês para organizar a saída da referência. A aprovação do protocolo é alta, mas a execução e a integração dos novos são incompletas.": "There is a month to organize the practice lead's departure. Protocol approval is high, but delivery and new-staff onboarding are incomplete.",
  "Qual lacuna precisa orientar a transição e o que não pode ser concluído a partir da aprovação?": "Which gap should guide the transition, and what cannot be concluded from approval?",
  "Distingam aceitabilidade, execução e continuidade com base nos dados.": "Distinguish acceptability, delivery and continuity using the data.",
  "O que será adaptado e monitorado antes e depois da saída da referência?": "What will be adapted and monitored before and after the practice lead leaves?",
  "Mapear dependências e organizar a transição": "Map dependencies and organize the transition",
  "Identificar tarefas concentradas na referência e construir um ciclo de apoio entre turnos.": "Identify tasks concentrated in the practice lead and build a support cycle across shifts.",
  "Enfrenta a continuidade e permite adaptar o processo. A transição precisa contemplar execução atual e recém-admitidos, além de distribuir nomes.": "This addresses continuity and allows process adaptation. The transition needs to cover current delivery and new staff, rather than simply assigning names.",
  "Priorizar integração dos profissionais novos": "Prioritize onboarding of new staff",
  "Criar uma experiência acompanhada da prática para quem ainda não participou.": "Create a supported practice experience for those who have not yet participated.",
  "Pode enfrentar uma lacuna dos destinatários. A saída da referência permanece um risco; expliquem quem acompanhará novas admissões depois da transição.": "This may address a recipient-related gap. The practice lead's departure remains a risk; explain who will support new hires after the transition.",
  "Preparar outra pessoa para assumir a referência": "Prepare another person to take over as practice lead",
  "Organizar uma passagem estruturada de responsabilidades para uma nova referência.": "Organize a structured handover of responsibilities to a new practice lead.",
  "Pode dar continuidade imediata, mas manter a dependência de uma única pessoa. Planejem como a organização sustentará o apoio em ausências e transferências futuras.": "This may provide immediate continuity but preserve dependence on a single person. Plan how the organization will sustain support during future absences and transfers.",
  "Investigar por que a aprovação não virou rotina": "Investigate why approval did not become routine practice",
  "Conversem com Rafael no posto e Marta no almoxarifado; leiam o memorando de Davi na sala da equipe. Comparem necessidades de aprendizagem, dependência pessoal e condições do apoio.": "Speak with Rafael at the nursing station and Marta in the supply room; read Davi's memo in the staff room. Compare learning needs, personal dependency and support conditions.",
  "Como relacionar determinantes individuais e organizacionais sem rotular a equipe como resistente?": "How can individual and organizational determinants be related without labeling staff as resistant?",
  "Quais pistas distinguem necessidades dos destinatários e condições organizacionais?": "Which clues distinguish recipients' needs from organizational conditions?",
  "Que hipótese é prioritária e como seria verificada antes de uma estratégia definitiva?": "Which hypothesis takes priority, and how would it be checked before choosing a definitive strategy?",
  "Priorizar integração e estrutura de apoio": "Prioritize onboarding and the support structure",
  "Examinar como recém-admitidos aprendem a prática e como o apoio será distribuído.": "Examine how new staff learn the practice and how support will be distributed.",
  "Os relatos sustentam essa prioridade. Definam quem oferece o apoio, como os turnos participam e que recursos são necessários para executar esse papel.": "The accounts support this priority. Define who provides support, how shifts participate and which resources are needed for this role.",
  "Priorizar incorporação ao fluxo organizacional": "Prioritize integration into organizational workflow",
  "Investigar responsabilidades, acompanhamento e integração do protocolo às rotinas existentes.": "Investigate responsibilities, monitoring and integration of the protocol into existing routines.",
  "Pode reduzir dependência pessoal. Uma rotina escrita não substitui preparo e escuta dos destinatários; incluam como necessidades dos novos serão identificadas.": "This may reduce personal dependency. A written routine does not replace preparation and listening to recipients; include how new staff's needs will be identified.",
  "Priorizar a capacidade dos facilitadores dos turnos": "Prioritize the capacity of shift facilitators",
  "Avaliar preparo, tempo e apoio de profissionais que podem facilitar a transição.": "Assess the preparation, time and support of staff who could facilitate the transition.",
  "A facilitação pode ficar mais próxima da prática. Sem pactuação institucional, esses profissionais podem acumular tarefas e abandonar o apoio.": "This may bring facilitation closer to practice. Without institutional agreement, these staff may accumulate tasks and abandon the support role.",
  "Distribuir facilitação com tempo limitado": "Distribute facilitation with limited time",
  "Davi aceita participar. Marta sairá mais cedo, e o apoio não poderá depender de encontros longos ou de contratação adicional.": "Davi agrees to participate. Marta will leave earlier, and support cannot depend on lengthy meetings or additional hiring.",
  "Que ações ativas de facilitação continuarão após a saída de Marta?": "Which active facilitation actions will continue after Marta leaves?",
  "Como inovação, destinatários e contexto orientam a divisão do apoio?": "How do innovation, recipients and context guide the distribution of support?",
  "Que responsabilidades e condições de trabalho serão pactuadas com a liderança?": "Which responsibilities and working conditions will be agreed with leadership?",
  "Apoio distribuído por turno dentro das rotinas existentes": "Distribute support across shifts within existing routines",
  "Preparar facilitadores locais, pactuar tempo breve na passagem do plantão e integrar novos profissionais.": "Prepare local facilitators, agree brief time during handover and onboard new staff.",
  "Pode ampliar cobertura e reduzir dependência pessoal. Definam preparação, limites do papel e apoio da liderança para que a atividade não seja apenas uma tarefa extra.": "This may broaden coverage and reduce personal dependency. Define preparation, role boundaries and leadership support so the activity is more than an extra task.",
  "Referência central com substitutos preparados": "Central practice lead with prepared deputies",
  "Manter uma referência e preparar substitutos, com materiais e critérios comuns de acompanhamento.": "Retain a practice lead and prepare deputies with shared materials and monitoring criteria.",
  "Pode preservar coordenação e consistência. A distribuição precisa ser real: expliquem quando os substitutos atuam e como serão apoiados.": "This may preserve coordination and consistency. Distribution must be real: explain when deputies act and how they receive support.",
  "Integração acompanhada e devolutivas periódicas": "Supported onboarding and periodic feedback",
  "Incluir prática acompanhada na integração e devolver dados de execução nas reuniões da unidade.": "Include supported practice in onboarding and provide delivery data at ward meetings.",
  "Cria mecanismos organizacionais de apoio. Indiquem quem conduz a integração, como o noturno participa e quem responde quando a execução se afasta do previsto.": "This creates organizational support mechanisms. Specify who leads onboarding, how the night shift participates and who responds when delivery deviates from the plan.",
  "Avaliar manutenção com denominadores que mudam": "Assess maintenance with changing denominators",
  "Seis meses após a saída de Marta, 18 de 30 profissionais atuais usam a prática na rotina definida pelo projeto. Dos 12 recém-admitidos nesse período, 4 a utilizam. Nos dados simulados, os 12 são parte dos 30.": "Six months after Marta leaves, 18 of the 30 current staff use the practice in the routine defined by the project. Of the 12 staff hired during this period, 4 use it. In these simulated data, the 12 are part of the 30.",
  "Como investigar manutenção organizacional e representatividade diante da rotatividade?": "How can organizational maintenance and representativeness be investigated in the presence of turnover?",
  "Definam uma medida, a fonte e o momento de acompanhamento.": "Define a measure, its source and the monitoring time point.",
  "Como analisar recém-admitidos e mudanças na composição da equipe?": "How will you analyze new hires and changes in staff composition?",
  "Acompanhar manutenção e integração dos novos": "Monitor maintenance and new-staff onboarding",
  "Examinar 18/30 no total e 4/12 entre novos, além das rotinas organizacionais de apoio.": "Examine 18/30 overall and 4/12 among new hires, together with organizational support routines.",
  "O total de 60% esconde 33,3% entre recém-admitidos; os demais são 14/18. Os grupos não demonstram causalidade e têm trajetórias diferentes. Investigem apoio e tempo de exposição.": "The overall 60% hides 33.3% among new hires; the remaining staff are 14/18. These groups do not establish causality and have different trajectories. Investigate support and exposure time.",
  "Investigar institucionalização da prática": "Investigate institutionalization of the practice",
  "Examinar integração, responsabilidades, apoio e orçamento após a saída da referência.": "Examine onboarding, responsibilities, support and budget after the practice lead leaves.",
  "O acompanhamento organizacional informa manutenção. Completem com dados de uso e execução para não confundir existência de uma rotina escrita com prática sustentada.": "Organizational monitoring informs maintenance. Add use and delivery data to avoid equating a written routine with sustained practice.",
  "Acompanhar uma coorte de profissionais ao longo do tempo": "Follow a cohort of staff over time",
  "Seguir os participantes iniciais e analisar perdas e mudanças de vínculo.": "Follow the initial participants and analyze attrition and changes in employment.",
  "Ajuda a compreender trajetórias individuais. Não descreve toda a organização após a rotatividade; incluam os profissionais novos e explicitem os denominadores.": "This helps explain individual trajectories. It does not describe the entire organization after turnover; include new hires and make denominators explicit.",
  "Defender sustentabilidade além de seis meses": "Defend sustainability beyond six months",
  "A prática continua, mas sua execução varia e os novos profissionais participam menos. A direção quer saber se é sustentável.": "The practice continues, but delivery varies and new staff participate less. Management wants to know whether it is sustainable.",
  "Que fontes permitem investigar sustentabilidade sem tratar um único ponto no tempo como prova definitiva?": "Which sources can investigate sustainability without treating a single time point as definitive proof?",
  "Definam como combinar uso, execução e mecanismos organizacionais em avaliações repetidas.": "Define how to combine use, delivery and organizational mechanisms in repeated assessments.",
  "Que resultado dispararia revisão do plano e quem seria responsável por agir?": "Which finding would trigger a plan review, and who would be responsible for acting?",
  "Avaliações repetidas de uso e apoio organizacional": "Repeated assessments of use and organizational support",
  "Combinar auditorias periódicas, integração dos novos e análise das responsabilidades e recursos.": "Combine periodic audits, new-staff onboarding and analysis of responsibilities and resources.",
  "A proposta pode investigar continuidade ao longo do tempo. Definam periodicidade e critérios de revisão; seis meses são um ponto de acompanhamento, não prova definitiva de sustentabilidade.": "This proposal can investigate continuity over time. Define frequency and review criteria; six months is a monitoring time point, rather than definitive proof of sustainability.",
  "Examinar incorporação nos subsistemas da unidade": "Examine integration into the ward's subsystems",
  "Investigar integração à admissão de profissionais, passagem de plantão e supervisão.": "Investigate integration into staff onboarding, shift handover and supervision.",
  "A integração e difusão podem informar penetração; sua continuidade informa sustentabilidade. Expliquem a distinção e acrescentem observação da execução.": "Integration and spread may inform penetration; their continuity informs sustainability. Explain the distinction and add observation of delivery.",
  "Avaliar viabilidade continuada e aceitabilidade dos novos": "Assess continued feasibility and acceptability among new staff",
  "Ouvir os profissionais e acompanhar condições de execução após cada mudança de equipe.": "Listen to staff and monitor delivery conditions after each staffing change.",
  "Esses desfechos podem explicar dificuldades de continuidade. Não substituem a medida de sustentabilidade; indiquem como os relacionarão ao uso ao longo do tempo.": "These outcomes may explain continuity difficulties. They do not replace a sustainability measure; specify how you will relate them to use over time.",
  "A equipe distinguiu aceitabilidade de execução?": "Did the team distinguish acceptability from delivery?",
  "A facilitação continuará sem depender de uma pessoa?": "Will facilitation continue without depending on one person?",
  "A avaliação inclui rotatividade, recém-admitidos e observações repetidas?": "Does the assessment include turnover, new hires and repeated observations?",
  "Knowledge-to-Action": "Knowledge-to-Action",
  "Como transformar conhecimento em ação?": "How can knowledge be turned into action?",
  "O KTA articula criação do conhecimento e um ciclo de ação. Identificar a lacuna, adaptar ao contexto, investigar barreiras, escolher estratégias, monitorar, avaliar e sustentar são atividades que podem ser revisitadas.": "KTA connects knowledge creation with an action cycle. Identifying the gap, adapting to context, investigating barriers, selecting strategies, monitoring, evaluating and sustaining are activities that can be revisited.",
  "Conhecimento": "Knowledge",
  "Sintetizar e preparar o conhecimento que será utilizado.": "Synthesize and prepare the knowledge to be used.",
  "Ação": "Action",
  "Adaptar, implementar e acompanhar o uso na prática.": "Adapt, implement and monitor use in practice.",
  "Iteração": "Iteration",
  "Voltar a uma etapa quando o contexto ou os resultados pedirem revisão.": "Return to an activity when context or findings call for revision.",
  "Tratar o ciclo como uma lista rígida ou presumir que publicar o protocolo encerra a implementação.": "Treating the cycle as a rigid checklist or assuming that publishing the protocol completes implementation.",
  "Graham et al., 2006": "Graham et al., 2006",
  "Modelo KTA e descrição do ciclo de ação": "KTA model and description of the action cycle",
  "O ciclo de ação prevê adaptação ao contexto, análise de barreiras e acompanhamento do uso.": "The action cycle includes contextual adaptation, barrier assessment and monitoring of use.",
  "Distinguir lacuna de registro e de execução orienta o primeiro teste.": "Distinguishing documentation and delivery gaps guides the first test.",
  "Investigar demanda e reposição permite adaptar o piloto aos recursos reais.": "Investigating demand and replenishment allows the pilot to fit actual resources.",
  "A saída de uma referência exige revisar apoio e continuidade.": "A practice lead's departure requires reviewing support and continuity.",
  "CFIR atualizado": "Updated CFIR",
  "Por que a prática encontra barreiras neste contexto?": "Why does this practice encounter barriers in this context?",
  "O CFIR organiza determinantes em cinco domínios. Serve para investigar barreiras e facilitadores; não escolhe automaticamente a estratégia nem substitui a avaliação dos resultados.": "CFIR organizes determinants into five domains. It supports investigation of barriers and facilitators; it does not automatically select a strategy or replace outcome evaluation.",
  "Inovação": "Innovation",
  "Características da prática ou tecnologia implementada.": "Characteristics of the practice or technology being implemented.",
  "Contexto externo": "Outer setting",
  "Condições do ambiente mais amplo.": "Conditions in the wider environment.",
  "Contexto interno": "Inner setting",
  "Condições do lugar em que a prática será implementada.": "Conditions where the practice will be implemented.",
  "Indivíduos": "Individuals",
  "Papéis e características das pessoas envolvidas.": "Roles and characteristics of the people involved.",
  "Processo": "Process",
  "Atividades do esforço de implementação.": "Activities within the implementation effort.",
  "Confundir uma barreira com a estratégia para enfrentá-la, ou classificar um relato sem definir o contexto do projeto.": "Confusing a barrier with the strategy to address it, or classifying an account without defining the project's context.",
  "Damschroder et al., 2022": "Damschroder et al., 2022",
  "Tabela 3: domínios e construtos atualizados": "Table 3: updated domains and constructs",
  "Reardon et al., 2025": "Reardon et al., 2025",
  "Passos 1–3: definir domínios, coletar e analisar dados": "Steps 1–3: define domains, collect and analyze data",
  "Os determinantes devem ser definidos para o projeto e investigados com dados antes de orientar a estratégia.": "Determinants should be defined for the project and investigated using data before they guide a strategy.",
  "Duplicidade, acesso e habilidades podem coexistir; comparem relatos e observação.": "Duplication, access and skills may coexist; compare accounts with observation.",
  "Criar estoque é estratégia; falta de recursos e fluxo inadequado são possíveis determinantes.": "Creating stock is a strategy; resource shortages and inadequate workflow are possible determinants.",
  "Aprovação não elimina necessidades dos recém-admitidos ou condições de apoio.": "Approval does not remove new staff's needs or support requirements.",
  "PARIHS e i-PARIHS": "PARIHS and i-PARIHS",
  "Quem ajuda as pessoas a incorporar a prática?": "Who helps people embed the practice?",
  "O PARIHS destaca evidência, contexto e facilitação. O i-PARIHS articula inovação, destinatários e contexto por meio da facilitação ativa: avaliar necessidades, alinhar condições e apoiar a mudança.": "PARIHS emphasizes evidence, context and facilitation. i-PARIHS connects innovation, recipients and context through active facilitation: assessing needs, aligning conditions and supporting change.",
  "A prática e suas características.": "The practice and its characteristics.",
  "Destinatários": "Recipients",
  "Pessoas e equipes afetadas pela implementação e que a influenciam.": "People and teams affected by implementation and influencing it.",
  "Contexto": "Context",
  "Condições locais, organizacionais e do sistema.": "Local, organizational and system conditions.",
  "Facilitação": "Facilitation",
  "Ações que aproximam inovação, pessoas e contexto.": "Actions that connect innovation, people and context.",
  "Designar uma facilitadora e presumir que o cargo, sem ações e apoio, resolve a implementação.": "Appointing a facilitator and assuming that the title, without action and support, resolves implementation.",
  "Harvey e Kitson, 2016": "Harvey and Kitson, 2016",
  "Tabela 2, Tabela 3 e seção The facilitation construct": "Table 2, Table 3 and The facilitation construct section",
  "A facilitação é o elemento ativo que avalia, alinha e integra inovação, destinatários e contexto.": "Facilitation is the active element that assesses, aligns and integrates innovation, recipients and context.",
  "Negociar um fluxo com os turnos é uma ação; nomear a facilitadora não basta.": "Negotiating a workflow across shifts is an action; appointing the facilitator is not enough.",
  "Apoiar a negociação entre abastecimento, destinatários e liderança conecta condições e prática.": "Supporting negotiation among supply staff, recipients and leadership connects conditions with practice.",
  "Preparar apoio distribuído envolve tempo, responsabilidades e acompanhamento.": "Preparing distributed support involves time, responsibilities and follow-up.",
  "RE-AIM": "RE-AIM",
  "Quem participa, o que acontece e o que continua?": "Who participates, what happens and what continues?",
  "O RE-AIM apoia planejamento e avaliação em níveis individual e organizacional. Definam unidade de análise, numerador, denominador, fonte e momento; investiguem também representatividade.": "RE-AIM supports planning and evaluation at individual and organizational levels. Define the unit of analysis, numerator, denominator, source and time point; also investigate representativeness.",
  "Alcance": "Reach",
  "Participação e perfil das pessoas destinatárias.": "Participation and characteristics of intended recipients.",
  "Efetividade": "Effectiveness",
  "Efeitos da intervenção, inclusive indesejados.": "Effects of the intervention, including unintended effects.",
  "Adoção": "Adoption",
  "Participação de serviços e profissionais que iniciam a prática.": "Participation of settings and staff who initiate the practice.",
  "Implementação": "Implementation",
  "Execução, adaptações e custos.": "Delivery, adaptations and costs.",
  "Manutenção": "Maintenance",
  "Continuidade em níveis individual e organizacional.": "Continuity at individual and organizational levels.",
  "Usar uma taxa global para ocultar grupos não alcançados, ou confundir adoção inicial com continuidade.": "Using an overall rate to hide groups not reached, or confusing initial adoption with continuity.",
  "Glasgow et al., 2019": "Glasgow et al., 2019",
  "Seção The RE-AIM dimensions: definitions, evolution, and examples": "The RE-AIM dimensions: definitions, evolution, and examples section",
  "As dimensões distinguem pessoas destinatárias, serviços/profissionais e continuidade; a representatividade importa.": "The dimensions distinguish recipients, settings/staff and continuity; representativeness matters.",
  "O total de alcance pode esconder diferenças entre turnos.": "Overall reach may hide differences between shifts.",
  "Três de quatro equipes iniciaram: adoção. Isso não comprova execução consistente.": "Three of four teams started: adoption. This does not establish consistent delivery.",
  "Denominadores e rotatividade precisam ser explicitados na análise da continuidade.": "Denominators and turnover need to be explicit when analyzing continuity.",
  "Desfechos de implementação": "Implementation outcomes",
  "Como investigar se a prática foi incorporada?": "How can we investigate whether the practice is embedded?",
  "A taxonomia de Proctor distingue resultados da implementação de resultados dos serviços e clínicos. Cada medida precisa indicar o que é avaliado, por quem, em que nível e momento.": "Proctor's taxonomy distinguishes implementation outcomes from service and clinical outcomes. Each measure must specify what is assessed, by whom, at which level and time point.",
  "Aceitabilidade": "Acceptability",
  "Percepção de que a prática é satisfatória.": "Perception that the practice is satisfactory.",
  "Intenção, decisão inicial ou início do uso.": "Intention, initial decision or initiation of use.",
  "Adequação": "Appropriateness",
  "Percepção de pertinência e compatibilidade.": "Perceived relevance and compatibility.",
  "Viabilidade": "Feasibility",
  "Possibilidade de executar no contexto.": "Possibility of delivering the practice in the context.",
  "Fidelidade": "Fidelity",
  "Execução conforme previsto.": "Delivery as intended.",
  "Custo": "Cost",
  "Impacto financeiro da implementação.": "Financial impact of implementation.",
  "Penetração": "Penetration",
  "Integração nos serviços e subsistemas.": "Integration within services and subsystems.",
  "Sustentabilidade": "Sustainability",
  "Manutenção ou institucionalização.": "Maintenance or institutionalization.",
  "Concluir que aprovar comprova usar, ou que melhora clínica, sozinha, comprova implementação.": "Concluding that approval establishes use, or that clinical improvement alone establishes implementation.",
  "Proctor et al., 2011": "Proctor et al., 2011",
  "Tabela 1 e seção Taxonomy of Implementation Outcomes": "Table 1 and Taxonomy of Implementation Outcomes section",
  "Proctor et al., 2023": "Proctor et al., 2023",
  "Conceptualization e discussão das relações entre estratégias e desfechos": "Conceptualization and discussion of relationships between strategies and outcomes",
  "Os desfechos são distintos e precisam de medidas específicas; relações causais requerem investigação.": "The outcomes are distinct and require specific measures; causal relationships require investigation.",
  "Registro e execução devem ser confrontados na medida de fidelidade.": "Documentation and delivery need to be compared when measuring fidelity.",
  "Adoção não substitui viabilidade; explicitem os recursos incrementais da implementação.": "Adoption does not replace feasibility; specify the incremental resources required for implementation.",
  "Observações repetidas e mecanismos organizacionais ajudam a investigar sustentabilidade.": "Repeated observations and organizational mechanisms help investigate sustainability."
};
