export type Question = {id:string; kind:'choice'|'match'|'order'; title:string; points:number; options:string[]; items?:string[]};
export type Round = {tag:string; title:string; lead:string; event:string; questions:Question[]; prompt:string; hint:string; source:number[]};
export const caseStory = 'O Hospital Horizonte, um serviço oncológico fictício, pretende implementar um protocolo de prevenção de lesão por pressão. Houve treinamento, mas o uso é irregular entre unidades e turnos. Sua equipe foi convidada a planejar a implementação, acompanhar o processo e avaliar a incorporação à rotina.';
export const teamNames = ['Equipe 1','Equipe 2','Equipe 3','Equipe 4'];
export const teamColors = ['#53d9c1','#ffb45b','#a7a2ff','#f780b6'];
export const criteriaLabels = ['Relaciona a proposta ao caso e ao referencial','Apresenta uma justificativa coerente','Propõe uma ação ou medida viável e específica'];
export const references = [
 {short:'Ferreira et al. · 2026',title:'Implementation science frameworks used to implement evidence-based practice in nursing: An integrative review',journal:'Applied Nursing Research, 90, 152109. Texto-base.',url:'https://doi.org/10.1016/j.apnr.2026.152109'},
 {short:'Graham et al. · 2006',title:'Lost in knowledge translation: time for a map?',journal:'Journal of Continuing Education in the Health Professions, 26(1), 13–24.',url:'https://doi.org/10.1002/chp.47'},
 {short:'Damschroder et al. · 2022',title:'The updated Consolidated Framework for Implementation Research based on user feedback',journal:'Implementation Science, 17, 75.',url:'https://doi.org/10.1186/s13012-022-01245-0'},
 {short:'Reardon et al. · 2025',title:'The CFIR User Guide: a five-step guide for conducting implementation research using the framework',journal:'Implementation Science.',url:'https://doi.org/10.1186/s13012-025-01450-7'},
 {short:'Harvey e Kitson · 2016',title:'PARIHS revisited: from heuristic to integrated framework for the successful implementation of knowledge into practice',journal:'Implementation Science, 11, 33.',url:'https://doi.org/10.1186/s13012-016-0398-2'},
 {short:'Glasgow et al. · 2019',title:'RE-AIM Planning and Evaluation Framework: Adapting to New Science and Practice With a 20-Year Review',journal:'Frontiers in Public Health, 7, 64.',url:'https://doi.org/10.3389/fpubh.2019.00064'},
 {short:'Proctor et al. · 2011',title:'Outcomes for Implementation Research: Conceptual Distinctions, Measurement Challenges, and Research Agenda',journal:'Administration and Policy in Mental Health, 38, 65–76.',url:'https://doi.org/10.1007/s10488-010-0319-7'},
 {short:'Proctor et al. · 2023',title:'Ten years of implementation outcomes research: a scoping review',journal:'Implementation Science, 18, 31.',url:'https://doi.org/10.1186/s13012-023-01286-z'},
 {short:'Hunter et al. · 2025',title:'Combined use of the i-PARIHS framework with other implementation frameworks: a systematic review',journal:'Implementation Science Communications, 6, 25.',url:'https://doi.org/10.1186/s43058-025-00704-1'},
];
export const rounds:Round[] = [
 {tag:'KTA',title:'Organizar a mudança',lead:'Um protocolo disponível ainda precisa se tornar prática cotidiana.',event:'A direção pede um novo treinamento geral. A equipe relata que não sabe quem deve registrar o risco e que o formulário não acompanha o fluxo do plantão.',source:[0,1],questions:[
 {id:'q1',kind:'order',title:'Organize a representação didática habitual do ciclo de ação do KTA.',points:3,options:['Monitorar o uso do conhecimento','Avaliar resultados','Adaptar o conhecimento ao contexto local','Sustentar o uso do conhecimento','Identificar a lacuna e selecionar evidências','Selecionar, adaptar e implementar estratégias','Avaliar barreiras e facilitadores']},
 {id:'q2',kind:'choice',title:'Antes de repetir o treinamento, qual ação é mais coerente com o caso?',points:2,options:['Investigar o fluxo, as responsabilidades e as barreiras com a equipe','Aplicar o mesmo treinamento sem investigar o contexto','Escolher apenas um indicador de resultado clínico']},
 {id:'q3',kind:'choice',title:'Qual é a principal contribuição do KTA neste projeto?',points:2,options:['Provar a eficácia clínica do protocolo','Orientar um processo iterativo de tradução do conhecimento em ação','Substituir a avaliação de resultados']},
 ],prompt:'Proponham uma adaptação ao fluxo do plantão e expliquem por que ela ajuda a transformar o protocolo em prática.',hint:'O ciclo não é uma sequência rígida: etapas podem se sobrepor e ser revisitadas.'},
 {tag:'CFIR',title:'Investigar o contexto',lead:'Identificar uma barreira é o primeiro passo para escolher uma estratégia pertinente.',event:'O formulário tem campos excessivos. A unidade dispõe de poucos materiais, e a liderança raramente discute o protocolo. Uma exigência externa de qualidade estimula sua adoção.',source:[0,2,3],questions:[
 {id:'q1',kind:'match',title:'Associe cada situação a um domínio do CFIR atualizado.',points:3,items:['Formulário complexo e difícil de utilizar','Exigência de qualidade de um órgão externo','Recursos disponíveis e apoio da liderança da unidade','Conhecimentos e necessidades dos profissionais envolvidos','Planejamento, engajamento e avaliação do projeto'],options:['Inovação','Contexto externo','Contexto interno','Indivíduos','Processo de implementação']},
 {id:'q2',kind:'choice',title:'Qual resposta enfrenta uma barreira do contexto interno?',points:2,options:['Responsabilizar individualmente todos os profissionais','Negociar recursos e tempo protegido com a liderança da unidade','Medir apenas a satisfação dos pacientes']},
 {id:'q3',kind:'choice',title:'O que a maior frequência de uso do CFIR na revisão permite afirmar?',points:2,options:['Que é superior a todos os outros frameworks','Que dispensa justificativa de escolha','Que foi mais utilizado nos estudos incluídos, sem demonstrar superioridade']},
 ],prompt:'Escolham uma barreira prioritária e proponham uma estratégia dirigida a ela. Justifiquem a relação entre barreira e estratégia.',hint:'O CFIR organiza determinantes. Sua escolha depende da pergunta; ele não é, sozinho, um roteiro completo de implementação.'},
 {tag:'i-PARIHS',title:'Facilitar a implementação',lead:'A mudança envolve uma inovação, pessoas e um contexto.',event:'O turno noturno não participou das decisões. A direção indica uma enfermeira facilitadora, mas ainda não definiu tempo, apoio ou como ela trabalhará com as equipes.',source:[0,4,8],questions:[
 {id:'q1',kind:'match',title:'Associe os elementos do caso aos construtos do i-PARIHS.',points:3,items:['Protocolo e suas características de uso','Equipes que adotam a prática e pacientes afetados','Condições da unidade, organização e sistema de saúde','Ações para alinhar a prática, as pessoas e o ambiente'],options:['Inovação','Destinatários','Contexto','Facilitação']},
 {id:'q2',kind:'choice',title:'Qual proposta representa melhor a facilitação?',points:2,options:['Entregar o protocolo e encerrar o apoio','Construir ajustes com os turnos, negociar barreiras e acompanhar o uso','Aplicar uma punição uniforme a quem não aderir']},
 {id:'q3',kind:'choice',title:'Qual afirmação distingue PARIHS e i-PARIHS?',points:2,options:['PARIHS: evidência, contexto e facilitação; i-PARIHS: inovação, destinatários, contexto e facilitação ativa','Os dois são escalas de resultado clínico','O i-PARIHS elimina o contexto e se concentra só na evidência']},
 ],prompt:'Descrevam uma ação concreta da facilitadora para incluir o turno noturno. Expliquem como ela considera destinatários e contexto.',hint:'Ser facilitador é um papel; fazer facilitação envolve ações contínuas e adaptadas à situação.'},
 {tag:'RE-AIM',title:'Avaliar o programa',lead:'Um bom resultado em uma unidade não garante alcance e manutenção em todo o serviço.',event:'Três das quatro unidades elegíveis iniciaram o protocolo. A equipe quer saber quem foi alcançado, como a prática foi executada e se continuará após o apoio inicial.',source:[0,5],questions:[
 {id:'q1',kind:'match',title:'Associe cada indicador a uma dimensão do RE-AIM.',points:3,items:['Proporção e perfil dos pacientes elegíveis alcançados pelo protocolo','Mudança na incidência de lesão por pressão e possíveis efeitos indesejados','Proporção e perfil das unidades que iniciaram o protocolo','Execução dos componentes, adaptações e custos de entrega','Continuidade e institucionalização da prática após o apoio inicial'],options:['Alcance','Efetividade','Adoção','Implementação','Manutenção']},
 {id:'q2',kind:'choice',title:'Três de quatro unidades elegíveis iniciaram o protocolo. Esse indicador se refere a:',points:2,options:['Alcance dos pacientes','Adoção pelas unidades','Efetividade clínica']},
 {id:'q3',kind:'choice',title:'Como investigar manutenção em nível organizacional?',points:2,options:['Verificar a continuidade e incorporação à rotina após seis meses','Contar participantes de um único treinamento','Avaliar apenas o primeiro dia de uso']},
 ],prompt:'Proponham um indicador de alcance OU adoção. Definam numerador, denominador, fonte dos dados e momento da avaliação.',hint:'Alcance se refere às pessoas destinatárias; adoção considera serviços e profissionais que iniciam a prática. Avaliem também representatividade.'},
 {tag:'DESFECHOS',title:'Demonstrar incorporação',lead:'Resultado clínico e resultado de implementação respondem a perguntas diferentes.',event:'Os profissionais dizem aprovar o protocolo, mas a auditoria encontra execução incompleta. A incidência de lesão por pressão caiu no período: isso, sozinho, não comprova a incorporação à rotina.',source:[0,6,7],questions:[
 {id:'q1',kind:'match',title:'Associe cada descrição a um desfecho de implementação de Proctor.',points:3,items:['Percepção de que a prática é satisfatória ou aceitável','Decisão ou início do uso da prática','Percepção de compatibilidade e pertinência para o problema e o contexto','Possibilidade de executar a prática no serviço','Execução conforme os componentes essenciais previstos','Recursos gastos para implementar a prática','Integração e difusão da prática na organização e em seus subsistemas','Continuidade do uso ao longo do tempo'],options:['Aceitabilidade','Adoção','Adequação','Viabilidade','Fidelidade','Custo de implementação','Penetração','Sustentabilidade']},
 {id:'q2',kind:'choice',title:'Qual é um indicador de fidelidade?',points:2,options:['Número de participantes no treinamento','Proporção de oportunidades auditadas com execução dos componentes essenciais','Incidência de lesão por pressão isoladamente']},
 {id:'q3',kind:'choice',title:'Uma equipe aprova o protocolo, mas quase não o utiliza. O que precisamos distinguir?',points:2,options:['Aceitabilidade e adoção: aprovar não equivale a iniciar o uso','Efetividade e custo: são o mesmo desfecho','Alcance e mortalidade: são indicadores equivalentes']},
 ],prompt:'Escolham um desfecho de implementação prioritário e descrevam como medi-lo, indicando quem será avaliado, fonte de dados e momento. Justifiquem a escolha.',hint:'A incidência de lesão por pressão é um resultado clínico. Não equivale a aceitabilidade, adoção ou fidelidade.'},
];
