export type Evidence={id:string;person:string;role:string;room:'kta'|'cfir'|'staff'|'facilitation'|'reaim';mode:'person'|'document';speech:string;finding:string};
export type Option={title:string;action:string;consequence:string};
export type Mission={title:string;brief:string;challenge:string;prompts:string[];options:Option[];requires?:string[]};
export type Case={title:string;problem:string;objectives:string[];data:{label:string;value:string;meaning:string}[];evidence:Evidence[];event:string;missions:Mission[];review:string[]};
export const institutionalProblem='O Hospital Horizonte publicou um protocolo de prevenção de lesão por pressão, mas sua incorporação varia entre unidades, turnos e profissionais. Treinamento e aprovação da equipe não garantiram execução consistente. Cada equipe deve investigar seu contexto e defender um plano de implementação, avaliação e continuidade.';
export const cases:Case[]=[
 {title:'O registro não conta toda a história',problem:'Na UTI oncológica, os registros sugerem adesão desigual entre os turnos. A direção quer um novo treinamento; os profissionais apontam duplicidade no prontuário. Ainda não sabemos quanto da lacuna é de documentação e quanto é de execução.',objectives:['Distinguir lacuna de registro e lacuna de execução','Priorizar determinantes do fluxo e dos turnos','Planejar um piloto e acompanhar alcance e fidelidade'],data:[
 {label:'Registro · diurno',value:'52/60',meaning:'Oportunidades elegíveis com avaliação de risco documentada'},
 {label:'Registro · noturno',value:'18/40',meaning:'Mesmo critério, em oportunidades elegíveis do turno noturno'},
 {label:'Observação direta',value:'16/30',meaning:'Oportunidades observadas com todos os componentes essenciais executados'},
 {label:'Treinamento',value:'28/32',meaning:'Profissionais elegíveis que participaram; isso não comprova execução'},
 ],evidence:[
 {id:'nurse',person:'Enfermeira Helena',role:'Enfermeira do diurno',room:'cfir',mode:'person',speech:'Eu registro o risco na evolução e novamente no formulário. Há colegas que fazem o cuidado, mas deixam uma das telas vazia.',finding:'A documentação pode subestimar parte da execução; investigar antes de atribuir a lacuna ao conhecimento.'},
 {id:'tech',person:'Técnico André',role:'Técnico do noturno',room:'staff',mode:'person',speech:'O formulário só abre no computador do posto. Durante os cuidados, anotamos em papel. A reunião de adaptação sempre acontece de manhã.',finding:'Acesso ao sistema e participação do noturno são condições do contexto e dos destinatários.'},
 {id:'audit',person:'Nota de Beatriz',role:'Registro escrito da auditora',room:'reaim',mode:'document',speech:'Na observação direta também faltaram componentes essenciais. Simplificar o registro pode ajudar, mas não podemos presumir que resolverá o cuidado.',finding:'Há indícios de duas lacunas: documentação e execução. Uma mudança de sistema precisa de medidas distintas.'},
 ],event:'A TI só poderá alterar o prontuário daqui a seis semanas. O noturno pede uma solução provisória sem um terceiro registro.',missions:[
 {title:'Escolher a lacuna e o primeiro teste',brief:'A direção oferece apoio para um piloto de duas semanas. Definam o que será investigado antes de expandir o projeto.',challenge:'Como iniciar a ação sem confundir ausência de registro com ausência de cuidado?',prompts:['Que lacuna será investigada e com quais fontes?','Como incluir os dois turnos e adaptar o conhecimento ao fluxo local?'],options:[
 {title:'Mapear registro e execução nos dois turnos',action:'Observar o processo e testar uma adaptação em pequena escala, comparando registro e execução.',consequence:'O piloto produz evidências úteis para adaptar a prática, mas exige tempo para observação e escuta. Definam quem participa e como evitar avaliar apenas o diurno.'},
 {title:'Começar pelo noturno e ampliar depois',action:'Concentrar inicialmente a investigação no turno com menor documentação.',consequence:'A prioridade atende uma lacuna visível. Porém, a documentação não descreve toda a execução; comparem fontes e explicitem o critério para ampliar o piloto ao diurno.'},
 {title:'Oferecer capacitação prática antes do piloto',action:'Realizar demonstração dos componentes essenciais e depois observar sua execução.',consequence:'A demonstração pode enfrentar uma necessidade de habilidade. Ainda falta confirmar essa barreira e lidar com duplicidade e acesso ao registro; evitem atribuir toda a lacuna à capacitação.'},
 ]},
 {title:'Confrontar as pistas do processo',brief:'Conversem com Helena no posto e André na sala da equipe; leiam a nota de Beatriz no núcleo de qualidade. As fontes descrevem explicações diferentes para a mesma taxa de registro.',challenge:'Que determinantes devem orientar a estratégia e qual hipótese ainda precisa ser verificada?',requires:['nurse','tech','audit'],prompts:['Relacionem duas pistas aos determinantes do CFIR e expliquem como se articulam.','Qual evidência confirmaria ou enfraqueceria a hipótese prioritária?'],options:[
 {title:'Priorizar fluxo do registro e participação dos turnos',action:'Mapear tarefas, acesso ao prontuário e participação do noturno antes de selecionar a adaptação.',consequence:'A estratégia dialoga com os relatos, mas a auditoria mostra execução incompleta. Expliquem como uma medida de cuidado acompanhará a mudança de registro.'},
 {title:'Priorizar conhecimentos e habilidades da equipe',action:'Investigar entendimento e execução dos componentes essenciais com observação e conversa.',consequence:'Pode existir uma necessidade de aprendizagem. Os dados de treinamento não comprovam competência, e as dificuldades do sistema continuam relevantes; expliquem como separar esses determinantes.'},
 {title:'Priorizar pactuação de responsabilidades',action:'Definir quem avalia, executa e confere cada componente na passagem do plantão.',consequence:'Responsabilidades claras podem apoiar a execução. Se a tela continuar inacessível e o noturno não participar, a pactuação pode virar apenas uma cobrança; descrevam as condições necessárias.'},
 ]},
 {title:'Facilitar sem criar mais trabalho',brief:'A facilitadora dispõe de dois encontros curtos por semana. A mudança do sistema depende da TI e não ocorrerá durante o piloto.',challenge:'Como articular inovação, destinatários e contexto diante dessa limitação?',prompts:['Que ação a facilitadora realizará com o noturno e a TI?','O que pode ser adaptado agora, preservando os componentes essenciais?'],options:[
 {title:'Cocriar um fluxo provisório entre os turnos',action:'Reunir representantes dos dois turnos, eliminar duplicidade autorizada e testar a organização do cuidado.',consequence:'O apoio considera os destinatários e o contexto. Confirmem com a instituição quais registros podem ser ajustados; uma solução provisória não deve gerar nova duplicidade.'},
 {title:'Aguardar a TI e preparar a mudança',action:'Usar o período para mapear necessidades, combinar responsabilidades e preparar um piloto do novo registro.',consequence:'Evita implantar uma solução temporária que será abandonada. A lacuna de cuidado pode persistir por seis semanas; defendam como será acompanhada durante a espera.'},
 {title:'Começar com acompanhamento na passagem do plantão',action:'A facilitadora acompanha o processo e dá devolutivas breves sobre os componentes essenciais.',consequence:'Oferece apoio imediato, mas depende do tempo e da presença da facilitadora. Planejem como o acompanhamento se distribuirá entre os turnos e continuará depois do piloto.'},
 ]},
 {title:'Construir um painel que não esconda o noturno',brief:'No piloto, 18 de 24 pacientes elegíveis receberam a prática. Foram 14 de 16 no diurno e 4 de 8 no noturno. Os dados são de pacientes distintos, atribuídos ao turno de sua primeira oportunidade no piloto.',challenge:'Que avaliação RE-AIM informa alcance e representatividade sem concluir eficácia a partir desses números?',prompts:['Definam numerador, denominador, fonte e momento para um indicador.','Que comparação é necessária para não esconder a diferença entre os turnos?'],options:[
 {title:'Mostrar alcance geral e por turno',action:'Apresentar 18/24 no total, 14/16 no diurno e 4/8 no noturno, com perfil dos pacientes.',consequence:'O alcance global é 75%, mas esconde uma diferença entre 87,5% e 50%. Verifiquem perfis e oportunidades antes de atribuir a diferença ao turno.'},
 {title:'Começar com alcance global e análise das perdas',action:'Usar 18/24 e investigar os seis pacientes não alcançados.',consequence:'A investigação das perdas pode identificar exclusões importantes. O total sozinho não mostra sua distribuição; indiquem como os turnos e os perfis serão examinados.'},
 {title:'Priorizar execução dos componentes no piloto',action:'Auditar componentes essenciais e adaptações, complementando a avaliação de implementação do RE-AIM.',consequence:'A execução é relevante, mas responde a uma dimensão diferente do alcance. Indiquem como saberão quem recebeu a prática e quem ficou de fora.'},
 ]},
 {title:'Defender fidelidade sem confundi-la com registro',brief:'O registro aumentou após o piloto. A direção quer declarar que o protocolo já foi incorporado. Sua equipe precisa defender como essa afirmação será investigada.',challenge:'Qual desfecho de implementação será prioritário e qual conclusão os dados ainda não permitem?',prompts:['Definam uma medida de fidelidade, incluindo componentes essenciais, fonte e periodicidade.','Que adaptação é aceitável e que mudança descaracterizaria a prática?'],options:[
 {title:'Combinar observação e auditoria de fidelidade',action:'Medir oportunidades com componentes essenciais executados / oportunidades elegíveis, conciliando fontes.',consequence:'A proposta distingue documentação de execução. Expliquem como selecionar oportunidades, lidar com divergências entre fontes e acompanhar os dois turnos.'},
 {title:'Usar o registro como sinal inicial de fidelidade',action:'Acompanhar a documentação e validar uma amostra por observação direta.',consequence:'Pode reduzir o esforço da avaliação. O registro só poderá representar a execução se essa relação for examinada; explicitem a amostra e os limites da conclusão.'},
 {title:'Investigar viabilidade antes de ampliar o piloto',action:'Examinar tempo, acesso ao sistema e condições para executar os componentes essenciais.',consequence:'A viabilidade pode orientar a expansão. Ela não comprova fidelidade; incluam uma medida complementar de execução e justifiquem a ordem das avaliações.'},
 ]},
 ],review:['A equipe distinguiu registro de execução?','A estratégia incluiu os dois turnos e preservou componentes essenciais?','O indicador permite investigar fidelidade sem inferir causalidade clínica?']},
 {title:'A prática depende de um abastecimento viável',problem:'Na clínica cirúrgica, duas de quatro equipes elegíveis iniciaram o protocolo. O abastecimento é irregular e buscar materiais consome tempo. Um estoque maior resolve parte do problema, mas pode aumentar perdas e custos.',objectives:['Distinguir início de adoção e execução cotidiana','Negociar uma estratégia compatível com recursos e fluxo','Avaliar adoção, viabilidade e custo de implementação'],data:[
 {label:'Equipes que iniciaram',value:'2/4',meaning:'Equipes elegíveis; início de uso, não execução contínua'},
 {label:'Abastecimento incompleto',value:'3/10 dias',meaning:'Dias do período observado com falta de pelo menos um material previsto'},
 {label:'Busca de material',value:'14 min',meaning:'Mediana de tempo por busca nas 12 buscas acompanhadas'},
 {label:'Custo adicional do piloto',value:'R$ 480',meaning:'Estimativa fictícia inicial; ainda sem tempo de trabalho e desperdício'},
 ],evidence:[
 {id:'supply',person:'Relatório de Paulo',role:'Registro de consumo e reposição',room:'facilitation',mode:'document',speech:'O consumo varia por cirurgia e ocupação. Um estoque fixo sem reposição pode faltar em um dia e vencer em outro.',finding:'O fluxo de reposição e a variação da demanda precisam compor a estratégia, além da quantidade em estoque.'},
 {id:'charge',person:'Enfermeira Lia',role:'Responsável pela unidade',room:'staff',mode:'person',speech:'Duas equipes começaram, mas não reservei tempo para conferir os materiais. Na alta demanda, o problema volta.',finding:'O início da adoção não assegura condições de execução; apoio organizacional e responsabilidades são relevantes.'},
 {id:'night',person:'Técnica Joana',role:'Plantão noturno cirúrgico',room:'staff',mode:'person',speech:'O estoque é conferido de manhã. Se falta à noite, a autorização demora e saímos da unidade para buscar.',finding:'A estratégia precisa considerar reposição e acesso durante a noite, não apenas o horário de conferência.'},
 ],event:'A instituição não aprovará contratação adicional neste mês. O orçamento do piloto permanece R$ 480 e deve incluir desperdício e tempo de trabalho.',missions:[
 {title:'Definir o problema além da falta de material',brief:'A direção oferece um piloto em uma equipe cirúrgica. A adoção inicial foi de 2/4 equipes, mas o abastecimento varia durante a semana.',challenge:'Que problema de implementação deve orientar o piloto e o que precisa ser adaptado?',prompts:['Qual lacuna será priorizada: início de uso, execução ou condições de abastecimento?','Que dados e participantes orientarão a adaptação ao contexto?'],options:[
 {title:'Mapear demanda e reposição antes de aumentar o estoque',action:'Investigar consumo, falta, tempo de busca e responsabilidades ao longo dos turnos.',consequence:'Permite adaptar a estratégia à demanda real. A investigação precisa ter prazo e uma resposta provisória para as faltas durante o piloto.'},
 {title:'Testar um estoque local limitado',action:'Criar uma pequena reserva na equipe piloto e acompanhar consumo, faltas e perdas.',consequence:'Pode reduzir deslocamentos rapidamente. Sem regra de reposição e controle de perdas, a reserva pode apenas deslocar o problema; definam critérios do teste.'},
 {title:'Começar com as duas equipes que ainda não adotaram',action:'Investigar por que não iniciaram a prática antes de ampliar a oferta de materiais.',consequence:'A pergunta sobre adoção é pertinente. Não presumam que as duas equipes que começaram já conseguem executar; comparem suas condições de trabalho.'},
 ]},
 {title:'Separar barreira de estratégia',brief:'Conversem com Lia e Joana na sala da equipe e consultem o relatório de Paulo no almoxarifado. Comparem problemas de demanda, gestão e acesso antes de priorizar.',challenge:'Como organizar os determinantes sem tratar “criar estoque” como se fosse uma barreira?',requires:['supply','charge','night'],prompts:['Identifiquem dois determinantes do CFIR sustentados pelos relatos.','Qual estratégia responde a cada determinante e qual risco pode permanecer?'],options:[
 {title:'Priorizar acesso aos recursos e fluxo de reposição',action:'Relacionar faltas e tempo de busca à disponibilidade de recursos e às condições do processo.',consequence:'Há sustentação nos relatos. O apoio da liderança e a pactuação de responsabilidades também precisam entrar no plano para que a reposição aconteça.'},
 {title:'Priorizar apoio organizacional e responsabilidades',action:'Negociar quem acompanha o abastecimento e como as decisões serão tomadas.',consequence:'Pode enfrentar a falta de tempo e de responsabilidade definida. Uma pactuação sem conhecer consumo e acesso no noturno pode continuar produzindo faltas.'},
 {title:'Priorizar a compatibilidade com os turnos',action:'Revisar horários de conferência e autorização em função do trabalho noturno.',consequence:'Enfrenta uma desigualdade do fluxo. Expliquem como a adaptação se integra ao abastecimento global, sem multiplicar estoques e perdas.'},
 ]},
 {title:'Negociar uma solução dentro do orçamento',brief:'O apoio financeiro inicial é limitado. A facilitadora pode articular a unidade e o abastecimento, mas não decide compras ou mudanças institucionais sozinha.',challenge:'Como tornar a prática executável sem uma solução dependente apenas de esforço individual?',prompts:['Que negociação a facilitadora fará com os destinatários e a liderança?','Como lidar com reposição noturna, tempo e desperdício?'],options:[
 {title:'Reserva local com reposição por consumo e limite de perdas',action:'Pactuar quantidade mínima, rotina de conferência e acesso noturno na equipe piloto.',consequence:'Pode equilibrar disponibilidade e perdas. Definam responsabilidades, regra de reposição e medida de custo; o estoque sozinho não é a facilitação.'},
 {title:'Distribuição programada por turno',action:'Combinar entrega ao início dos turnos com um fluxo de contingência para demanda extra.',consequence:'Pode reduzir estoques dispersos. A demanda cirúrgica varia; a contingência precisa funcionar à noite e ter responsável definido.'},
 {title:'Manter estoque central com acesso simplificado',action:'Negociar autorização e retirada rápidas, acompanhando o tempo de busca.',consequence:'Pode limitar desperdício local, mas deslocamentos permanecem. Defendam em que condições essa opção é viável e como o tempo será considerado.'},
 ]},
 {title:'Avaliar adoção sem esconder execução e custos',brief:'Após o piloto, três de quatro equipes elegíveis iniciaram o protocolo. Uma nova equipe ainda enfrenta faltas; foram gastos R$ 720, considerando materiais, tempo e perdas.',challenge:'Que dimensões do RE-AIM ajudam a avaliar o avanço e seus limites?',prompts:['Definam uma medida de adoção com numerador, denominador e fonte.','Que informações de implementação e custo complementam essa medida?'],options:[
 {title:'Adoção das equipes junto de execução e custos',action:'Apresentar 3/4 equipes, examinar seus perfis e acompanhar faltas, componentes executados e custos.',consequence:'A adoção passou a 75%; isso não comprova execução consistente. O custo real superou a estimativa inicial, cuja composição era incompleta; explicitem ambas as bases.'},
 {title:'Adoção com foco nas equipes que ficaram de fora',action:'Apresentar 3/4 e investigar condições da quarta equipe para uma expansão posterior.',consequence:'A investigação das não adotantes informa representatividade e expansão. Acrescentem como avaliar a prática nas três que começaram e os recursos necessários.'},
 {title:'Avaliação detalhada da implementação no piloto',action:'Acompanhar faltas, adaptações, tempo e custo na equipe piloto antes de ampliar.',consequence:'Produz informações de execução, mas ainda não descreve adoção no conjunto do serviço. Expliquem como combinar o piloto com o panorama das quatro equipes.'},
 ]},
 {title:'Defender viabilidade e custo de implementação',brief:'A direção quer expandir com base no aumento de adoção. A equipe deve apresentar se a solução é executável e quais recursos exige.',challenge:'Que desfechos permitem decidir sobre expansão sem equiparar adoção, viabilidade e resultado clínico?',prompts:['Descrevam como avaliar viabilidade: pessoas, fluxo, fonte e momento.','Quais componentes entrarão no custo de implementação e como serão separados dos custos assistenciais habituais?'],options:[
 {title:'Triangular viabilidade com uma estimativa completa de custo',action:'Combinar relatos, observação do fluxo e registros de recursos usados especificamente na implementação.',consequence:'As fontes podem revelar dificuldades que a adoção não mostra. Definam período, perspectiva e quais custos são incrementais; não somem indistintamente toda a assistência.'},
 {title:'Testar a viabilidade em alta e baixa demanda',action:'Comparar tempo, faltas e execução em períodos distintos antes da expansão.',consequence:'A variação da demanda é importante. A comparação não isola efeito causal e precisa considerar ocupação, perfil cirúrgico e recursos usados em cada período.'},
 {title:'Expandir gradualmente com monitoramento de viabilidade',action:'Incluir uma nova equipe por vez, mantendo critérios de revisão do fluxo e dos custos.',consequence:'Permite aprender durante a expansão, mas expõe novas equipes a dificuldades do fluxo. Definam quando interromper, ajustar ou continuar a expansão.'},
 ]},
 ],review:['O plano distingue adoção inicial de execução?','A facilitação inclui liderança, abastecimento e noturno?','A avaliação de viabilidade e custo considera demanda, tempo e perdas?']},
 {title:'A prática precisa sobreviver à saída da referência',problem:'Na internação, profissionais aprovam o protocolo, mas o uso depende de uma enfermeira de referência. Ela sairá da unidade em um mês. A rotatividade e a integração incompleta dos recém-admitidos ameaçam a continuidade.',objectives:['Distinguir aceitabilidade, adoção e execução','Distribuir a facilitação e integrar recém-admitidos','Planejar manutenção e avaliar sustentabilidade'],data:[
 {label:'Aprovação do protocolo',value:'22/24',meaning:'Respondentes que o consideraram aceitável; não é medida de uso'},
 {label:'Execução observada',value:'15/40',meaning:'Oportunidades observadas com componentes essenciais executados'},
 {label:'Integração dos novos',value:'6/12',meaning:'Recém-admitidos elegíveis incluídos na apresentação e prática acompanhada'},
 {label:'Saída da referência',value:'30 dias',meaning:'Prazo para organizar continuidade antes da transferência da enfermeira'},
 ],evidence:[
 {id:'new',person:'Enfermeiro Rafael',role:'Recém-admitido',room:'cfir',mode:'person',speech:'Recebi o PDF na integração, mas nunca acompanhei o fluxo com alguém. Quando tenho dúvida, espero a enfermeira de referência chegar.',finding:'Aceitar a prática não elimina necessidades dos destinatários; a integração atual oferece informação, mas pouco apoio à execução.'},
 {id:'champion',person:'Enfermeira Marta',role:'Referência que será transferida',room:'facilitation',mode:'person',speech:'Eu cobro o registro e reorganizo os cuidados toda manhã. Ainda não combinamos quem fará isso quando eu sair.',finding:'A continuidade está concentrada em uma pessoa, sem papel distribuído ou rotina organizacional definida.'},
 {id:'leader',person:'Memorando de Davi',role:'Registro da liderança noturna',room:'staff',mode:'document',speech:'Podemos assumir parte do apoio, mas precisamos de tempo e saber quais ajustes são permitidos. A integração dos novos ocorre só no diurno.',finding:'Há disponibilidade para facilitação distribuída, condicionada a apoio, preparação e inclusão dos turnos.'},
 ],event:'Marta sairá uma semana antes do previsto. Chegarão quatro profissionais novos no próximo mês e não haverá aumento de carga horária.',missions:[
 {title:'Planejar uma transição com propósito',brief:'Há um mês para organizar a saída da referência. A aprovação do protocolo é alta, mas a execução e a integração dos novos são incompletas.',challenge:'Qual lacuna precisa orientar a transição e o que não pode ser concluído a partir da aprovação?',prompts:['Distingam aceitabilidade, execução e continuidade com base nos dados.','O que será adaptado e monitorado antes e depois da saída da referência?'],options:[
 {title:'Mapear dependências e organizar a transição',action:'Identificar tarefas concentradas na referência e construir um ciclo de apoio entre turnos.',consequence:'Enfrenta a continuidade e permite adaptar o processo. A transição precisa contemplar execução atual e recém-admitidos, além de distribuir nomes.'},
 {title:'Priorizar integração dos profissionais novos',action:'Criar uma experiência acompanhada da prática para quem ainda não participou.',consequence:'Pode enfrentar uma lacuna dos destinatários. A saída da referência permanece um risco; expliquem quem acompanhará novas admissões depois da transição.'},
 {title:'Preparar outra pessoa para assumir a referência',action:'Organizar uma passagem estruturada de responsabilidades para uma nova referência.',consequence:'Pode dar continuidade imediata, mas manter a dependência de uma única pessoa. Planejem como a organização sustentará o apoio em ausências e transferências futuras.'},
 ]},
 {title:'Investigar por que a aprovação não virou rotina',brief:'Conversem com Rafael no posto e Marta no almoxarifado; leiam o memorando de Davi na sala da equipe. Comparem necessidades de aprendizagem, dependência pessoal e condições do apoio.',challenge:'Como relacionar determinantes individuais e organizacionais sem rotular a equipe como resistente?',requires:['new','champion','leader'],prompts:['Quais pistas distinguem necessidades dos destinatários e condições organizacionais?','Que hipótese é prioritária e como seria verificada antes de uma estratégia definitiva?'],options:[
 {title:'Priorizar integração e estrutura de apoio',action:'Examinar como recém-admitidos aprendem a prática e como o apoio será distribuído.',consequence:'Os relatos sustentam essa prioridade. Definam quem oferece o apoio, como os turnos participam e que recursos são necessários para executar esse papel.'},
 {title:'Priorizar incorporação ao fluxo organizacional',action:'Investigar responsabilidades, acompanhamento e integração do protocolo às rotinas existentes.',consequence:'Pode reduzir dependência pessoal. Uma rotina escrita não substitui preparo e escuta dos destinatários; incluam como necessidades dos novos serão identificadas.'},
 {title:'Priorizar a capacidade dos facilitadores dos turnos',action:'Avaliar preparo, tempo e apoio de profissionais que podem facilitar a transição.',consequence:'A facilitação pode ficar mais próxima da prática. Sem pactuação institucional, esses profissionais podem acumular tarefas e abandonar o apoio.'},
 ]},
 {title:'Distribuir facilitação com tempo limitado',brief:'Davi aceita participar. Marta sairá mais cedo, e o apoio não poderá depender de encontros longos ou de contratação adicional.',challenge:'Que ações ativas de facilitação continuarão após a saída de Marta?',prompts:['Como inovação, destinatários e contexto orientam a divisão do apoio?','Que responsabilidades e condições de trabalho serão pactuadas com a liderança?'],options:[
 {title:'Apoio distribuído por turno dentro das rotinas existentes',action:'Preparar facilitadores locais, pactuar tempo breve na passagem do plantão e integrar novos profissionais.',consequence:'Pode ampliar cobertura e reduzir dependência pessoal. Definam preparação, limites do papel e apoio da liderança para que a atividade não seja apenas uma tarefa extra.'},
 {title:'Referência central com substitutos preparados',action:'Manter uma referência e preparar substitutos, com materiais e critérios comuns de acompanhamento.',consequence:'Pode preservar coordenação e consistência. A distribuição precisa ser real: expliquem quando os substitutos atuam e como serão apoiados.'},
 {title:'Integração acompanhada e devolutivas periódicas',action:'Incluir prática acompanhada na integração e devolver dados de execução nas reuniões da unidade.',consequence:'Cria mecanismos organizacionais de apoio. Indiquem quem conduz a integração, como o noturno participa e quem responde quando a execução se afasta do previsto.'},
 ]},
 {title:'Avaliar manutenção com denominadores que mudam',brief:'Seis meses após a saída de Marta, 18 de 30 profissionais atuais usam a prática na rotina definida pelo projeto. Dos 12 recém-admitidos nesse período, 4 a utilizam. Nos dados simulados, os 12 são parte dos 30.',challenge:'Como investigar manutenção organizacional e representatividade diante da rotatividade?',prompts:['Definam uma medida, a fonte e o momento de acompanhamento.','Como analisar recém-admitidos e mudanças na composição da equipe?'],options:[
 {title:'Acompanhar manutenção e integração dos novos',action:'Examinar 18/30 no total e 4/12 entre novos, além das rotinas organizacionais de apoio.',consequence:'O total de 60% esconde 33,3% entre recém-admitidos; os demais são 14/18. Os grupos não demonstram causalidade e têm trajetórias diferentes. Investigem apoio e tempo de exposição.'},
 {title:'Investigar institucionalização da prática',action:'Examinar integração, responsabilidades, apoio e orçamento após a saída da referência.',consequence:'O acompanhamento organizacional informa manutenção. Completem com dados de uso e execução para não confundir existência de uma rotina escrita com prática sustentada.'},
 {title:'Acompanhar uma coorte de profissionais ao longo do tempo',action:'Seguir os participantes iniciais e analisar perdas e mudanças de vínculo.',consequence:'Ajuda a compreender trajetórias individuais. Não descreve toda a organização após a rotatividade; incluam os profissionais novos e explicitem os denominadores.'},
 ]},
 {title:'Defender sustentabilidade além de seis meses',brief:'A prática continua, mas sua execução varia e os novos profissionais participam menos. A direção quer saber se é sustentável.',challenge:'Que fontes permitem investigar sustentabilidade sem tratar um único ponto no tempo como prova definitiva?',prompts:['Definam como combinar uso, execução e mecanismos organizacionais em avaliações repetidas.','Que resultado dispararia revisão do plano e quem seria responsável por agir?'],options:[
 {title:'Avaliações repetidas de uso e apoio organizacional',action:'Combinar auditorias periódicas, integração dos novos e análise das responsabilidades e recursos.',consequence:'A proposta pode investigar continuidade ao longo do tempo. Definam periodicidade e critérios de revisão; seis meses são um ponto de acompanhamento, não prova definitiva de sustentabilidade.'},
 {title:'Examinar incorporação nos subsistemas da unidade',action:'Investigar integração à admissão de profissionais, passagem de plantão e supervisão.',consequence:'A integração e difusão podem informar penetração; sua continuidade informa sustentabilidade. Expliquem a distinção e acrescentem observação da execução.'},
 {title:'Avaliar viabilidade continuada e aceitabilidade dos novos',action:'Ouvir os profissionais e acompanhar condições de execução após cada mudança de equipe.',consequence:'Esses desfechos podem explicar dificuldades de continuidade. Não substituem a medida de sustentabilidade; indiquem como os relacionarão ao uso ao longo do tempo.'},
 ]},
 ],review:['A equipe distinguiu aceitabilidade de execução?','A facilitação continuará sem depender de uma pessoa?','A avaliação inclui rotatividade, recém-admitidos e observações repetidas?']},
];
