'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,BookOpen,Check,ClipboardList,DoorOpen,Flag,MapPin,MessageCircle,RotateCcw,Users,Smartphone,Volume2,VolumeX,FileText,Timer,Pause,Play,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect} from '@/components/ui/native-select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {cases,institutionalProblem,type Mission,type Evidence} from '@/lib/hospital-missions';
import {actors,findPath,freshTeams,missionNames,rooms,stageRooms,walkable,commitDecision,ambientPeople,ambientPosition,type Point,type TeamState} from '@/lib/hospital-preview';
import {references} from '@/lib/game-data';
import {frameworkTopics} from '@/lib/hospital-consultant';
import {ringPhone} from '@/lib/hospital-sound';
import {GAME_SECONDS,PLAYER_SPEED,KEY_STEP,roomPoints,evidencePoint,secondsLeft,timerLabel,studyFiles} from '@/lib/hospital-session';
import {Consultant,FacultyBoard} from './hospital-widgets';
import './hospital.css';
import {InvitationList,type OnlineRoom} from './room-client';
import {initialPositions} from '../worker/session';
const starts:Point[]=initialPositions();
function EvidenceCard({evidence:e,discovered,disabled,onRecord}:{evidence:Evidence;discovered:boolean;disabled:boolean;onRecord:()=>void}){return <article className={`hp-evidence-card ${e.mode==='document'?'is-document':''}`}><div className="hp-conversation">{e.mode==='document'?<FileText size={31}/>:<Sprite index={5}/>}<div><strong>{e.person} · {e.role}</strong><p>{e.mode==='document'?e.speech:`“${e.speech}”`}</p></div></div><button className="hp-evidence-button" disabled={disabled} onClick={onRecord}>{discovered?<Check size={16}/>:e.mode==='document'?<FileText size={16}/>:<MessageCircle size={16}/>} {discovered?'Fonte registrada':e.mode==='document'?'Registrar a evidência do documento':'Registrar o relato'}</button>{discovered&&<div className="hp-info">{e.finding}</div>}</article>;}
const firstMessage='Clique no piso para caminhar. Os marcadores abrem conversas quando você chega perto.';
type Draft={choice:number;memo:string};
function MissionEditor({mission,stage,teamId,state,draft,onDraft,onSave,disabled,meeting,onVisit,onConsult}:{mission:Mission;stage:number;teamId:number;state:TeamState;draft:Draft;onDraft:(d:Draft)=>void;onSave:()=>void;disabled:boolean;meeting:boolean;onVisit:(id:string)=>void;onConsult:()=>void}){
 const missing=(mission.requires||[]).filter(id=>!state.clues.includes(id));const unlocked=state.stage>=stage&&(stage<4||meeting)&&(stage<3||!state.eventDelivered||state.eventRead);
 const label=frameworkTopics[stage].name;
 return <section className="hp-mission-editor"><span className="hp-overline">{label}</span><h3>{mission.title}</h3><p>{mission.brief}</p><div className="hp-challenge"><strong>Decisão da equipe</strong><p>{mission.challenge}</p></div><button className="hp-consultant-call" onClick={onConsult}><img src="/hospital-preview/consultant.png" alt=""/><span><strong>Pedir orientação à consultora Iris</strong><small>Entender {label} e relacionar ao caso</small></span></button>{missing.length>0&&<div className="hp-clue-check"><strong>Confrontem conversas e documentos antes de fechar a hipótese</strong>{cases[teamId].evidence.map(e=><button key={e.id} onClick={()=>onVisit(e.room)}><span>{state.clues.includes(e.id)?<Check size={16}/>:<MessageCircle size={16}/>}</span>{e.person}<small>{e.mode==='document'?'Documento · ':''}{rooms.find(r=>r.id===e.room)?.name}</small></button>)}</div>}{!unlocked&&<div className="hp-info">{stage>=3&&state.eventDelivered&&!state.eventRead?'Leiam o comunicado no celular da coordenação antes de registrar a próxima decisão.':stage===4?'O professor ou o seminário convoca o encontro após as quatro etapas iniciais das três equipes.':'Concluam a etapa anterior antes de registrar esta decisão. Vocês já podem explorar as pistas.'}</div>}<RadioGroup value={String(draft.choice)} onValueChange={v=>onDraft({...draft,choice:Number(v)})} disabled={disabled||!unlocked||missing.length>0} aria-label="Estratégia escolhida pela equipe" className="hp-decision-options">{mission.options.map((o,i)=><label key={i} className={draft.choice===i?'selected':''}><RadioGroupItem value={String(i)}/><span><strong>{o.title}</strong><small>{o.action}</small></span></label>)}</RadioGroup><div className="hp-memo"><h4>Conversa da equipe · registro do plano</h4><ul>{mission.prompts.map(p=><li key={p}>{p}</li>)}</ul><label htmlFor={`memo-${teamId}-${stage}`}>Registrem a justificativa, a evidência usada e o que precisa ser acompanhado.</label><textarea id={`memo-${teamId}-${stage}`} value={draft.memo} maxLength={1200} disabled={disabled||!unlocked} onChange={e=>onDraft({...draft,memo:e.target.value})} placeholder="Relacionem a escolha aos dados e relatos do caso. Incluam uma limitação ou condição para o plano funcionar." rows={4}/><small>{draft.memo.trim().length}/1200 caracteres · registro breve, mínimo de 30</small><button className="hp-primary" disabled={disabled||!unlocked||missing.length>0||draft.choice<0||draft.memo.trim().length<30} onClick={onSave}>{state.decisions[stage]?'Revisar decisão e justificativa':'Pactuar plano e observar consequência'}</button><p className="hp-review-note">Não há nota automática para a justificativa. O professor discute a coerência entre evidência, estratégia e avaliação.</p></div>{state.decisions[stage]&&<div className="hp-consequence"><strong>Consequência e ponto a acompanhar</strong><p>{state.decisions[stage].consequence}</p></div>}</section>;
}
function Sprite({index}:{index:number}){return <span className="hp-sprite" style={{backgroundPosition:`${(index%6)*20}% center`}}/>;}
export default function HospitalGame({online,onLeave}:{online:OnlineRoom|null;onLeave:()=>void}){
 const [active,setActive]=useState(online?.me.actor??online?.me.team??0),[inspect,setInspect]=useState(0),[positions,setPositions]=useState<Point[]>(starts),[teams,setTeams]=useState<TeamState[]>(freshTeams),[spot,setSpot]=useState<string|null>(null),[message,setMessage]=useState(firstMessage),[journal,setJournal]=useState(false),[source,setSource]=useState(false),[meeting,setMeeting]=useState(false),[menu,setMenu]=useState(false);
 const [drafts,setDrafts]=useState<Record<string,Draft>>({}),[notice,setNotice]=useState(''),[reviewDraft,setReviewDraft]=useState(''),[consultTopic,setConsultTopic]=useState(0),[sound,setSound]=useState(true),[ambientTime,setAmbientTime]=useState(0);
 const [remaining,setRemaining]=useState(GAME_SECONDS),[deadline,setDeadline]=useState<number|null>(null),[debriefClosed,setDebriefClosed]=useState(false);
 useEffect(()=>{if(deadline===null)return;const tick=()=>{const left=secondsLeft(deadline,Date.now());setRemaining(left);if(left===0)setDeadline(null);};tick();const id=window.setInterval(tick,250);return()=>window.clearInterval(id);},[deadline]);
 function toggleTimer(){if(online){online.send({type:'timer'});return;}if(deadline!==null){setRemaining(secondsLeft(deadline,Date.now()));setDeadline(null);}else if(remaining>0)setDeadline(Date.now()+remaining*1000);}
 function conclude(){if(!mediator||!finished)return;if(online){online.send({type:'release'});return;}setDebriefClosed(true);setDeadline(null);if(deadline!==null)setRemaining(secondsLeft(deadline,Date.now()));setSpot('delivery');setMessage('Iris está entregando os resumos de estudo. Cada participante pode baixar o material de sua equipe.');}
 const audioRef=useRef<AudioContext|null>(null),ringed=useRef(new Set<number>()),soundRef=useRef(true),lastRoom=useRef<string>('kta'),receipts=useRef(new Set<number>()),clockRef=useRef(0),reducedRef=useRef(false);
 useEffect(()=>{soundRef.current=sound;},[sound]);
 useEffect(()=>{reducedRef.current=window.matchMedia('(prefers-reduced-motion: reduce)').matches;return()=>{void audioRef.current?.close();};},[]);
 const onlineRef=useRef(online),received=useRef(false),meetingRef=useRef(false),lastSent=useRef(0),lastSentPoint=useRef<Point|null>(null);
 useEffect(()=>{onlineRef.current=online;},[online]);
 const activeRef=useRef(active),posRef=useRef(positions),spotRef=useRef(spot),route=useRef<Point[]>([]),arrival=useRef<string|null>(null),mapRef=useRef<HTMLDivElement>(null);
 const spectator=online?.me.kind==='viewer',canMove=!online||online.me.actor!==null;
 const mediator=active>=3,teamId=mediator?inspect:active,t=teams[teamId],caseData=cases[teamId],currentRoom=rooms.find(r=>r.id===spot),evidence=caseData.evidence.find(e=>spot===`evidence:${e.id}`),ready=teams.every(t=>t.stage>=4),finished=teams.every(t=>t.complete);
 useEffect(()=>{activeRef.current=active;route.current=[];arrival.current=null;},[active]);
 useEffect(()=>{if(!online?.snapshot)return;const data=online.snapshot;setTeams(data.teams);setMeeting(data.meeting);setDebriefClosed(data.released);setRemaining(data.timer.remaining);setDeadline(data.timer.deadline===null?null:data.timer.deadline-online.offset);if(!received.current||meetingRef.current!==data.meeting){setPositions(data.positions);posRef.current=data.positions;route.current=[];arrival.current=null;received.current=true;}meetingRef.current=data.meeting;if(data.released)setMessage('Iris está entregando os resumos. Cada integrante pode baixar o material da sua equipe.');const own=online.me.team;if(own!==null&&data.teams[own].eventDelivered&&!ringed.current.has(own)){ringed.current.add(own);playRing();setMessage('A coordenação enviou um comunicado. Consulte o celular no mapa.');}},[online?.snapshot]);
 useEffect(()=>{if(!online?.positions.length)return;const all=online.positions.map((p,i)=>i===online.me.actor?posRef.current[i]:p);posRef.current=all;setPositions(all);},[online?.positions]);
 useEffect(()=>{if(debriefClosed&&active<3&&!receipts.current.has(active)){receipts.current.add(active);setSpot('delivery');}},[debriefClosed,active]);
 useEffect(()=>{posRef.current=positions;},[positions]);useEffect(()=>{spotRef.current=spot||((journal||source||menu)?'modal':null);},[spot,journal,source,menu]);
 useEffect(()=>{setNotice('');setReviewDraft(teams[teamId].review);},[spot,teamId]);
 useEffect(()=>{let handle:number,last=0;function tick(now:number){if(!spotRef.current&&now-clockRef.current>80&&!reducedRef.current){clockRef.current=now;setAmbientTime(onlineRef.current?Date.now()/1000:now/1000);}const dt=Math.min((now-last)/1000,.045);last=now;const id=activeRef.current,p=posRef.current[id],target=route.current[0];if(target&&!spotRef.current&&(!onlineRef.current||onlineRef.current.connected)){const d=Math.hypot(target.x-p.x,target.y-p.y),step=PLAYER_SPEED*dt;const next=d<=step?target:{x:p.x+(target.x-p.x)/d*step,y:p.y+(target.y-p.y)/d*step};const all=[...posRef.current];all[id]=next;posRef.current=all;setPositions(all);if(d<=step){route.current.shift();if(!route.current.length&&arrival.current){setSpot(arrival.current);arrival.current=null;}}}const live=onlineRef.current;if(live?.connected&&live.me.actor!==null&&now-lastSent.current>=200){const p=posRef.current[live.me.actor];if(!lastSentPoint.current||Math.hypot(p.x-lastSentPoint.current.x,p.y-lastSentPoint.current.y)>1){live.send({type:'move',x:p.x,y:p.y});lastSentPoint.current={...p};lastSent.current=now;}}handle=requestAnimationFrame(tick);}handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[]);
 function updateTeam(fn:(state:TeamState)=>TeamState){setTeams(old=>old.map((state,i)=>i===teamId?fn(state):state));}
 function go(point:Point,roomId?:string){if(!canMove){if(roomId)setSpot(roomId);return;}if(online&&!online.connected){setMessage('Aguarde a conexão para caminhar.');return;}const p=posRef.current[activeRef.current];if(Math.hypot(p.x-point.x,p.y-point.y)<30&&roomId){setSpot(roomId);return;}const path=findPath(p,point);if(!path.length){setMessage('Esse ponto não tem passagem. Escolha o piso do corredor ou uma sala.');return;}route.current=path;arrival.current=roomId||null;setMessage(roomId?`Caminhando até ${rooms.find(r=>r.id===roomId)?.name|| (roomId==='consultant'?'Iris':roomId==='phone'?'o celular da coordenação':'a fonte de informação')}…`:'Caminhando…');mapRef.current?.focus();}
 function move(dx:number,dy:number){if(!canMove||online&&!online.connected)return;const p=posRef.current[activeRef.current],n={x:p.x+dx*KEY_STEP,y:p.y+dy*KEY_STEP};if(walkable(n)){route.current=[];arrival.current=null;setPositions(old=>old.map((v,i)=>i===activeRef.current?n:v));}}
 useEffect(()=>{function key(e:KeyboardEvent){if(onlineRef.current&&(onlineRef.current.me.actor===null||!onlineRef.current.connected))return;if(spotRef.current||['INPUT','TEXTAREA','SELECT','BUTTON'].includes((e.target as HTMLElement)?.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;const deltas:Record<string,[number,number]>={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};if(deltas[e.key]){e.preventDefault();const p=posRef.current[activeRef.current],n={x:p.x+deltas[e.key][0]*KEY_STEP,y:p.y+deltas[e.key][1]*KEY_STEP};if(walkable(n)){route.current=[];arrival.current=null;const all=[...posRef.current];all[activeRef.current]=n;posRef.current=all;setPositions(all);}}if(e.key.toLowerCase()==='e'){const p=posRef.current[activeRef.current];const close=rooms.find(r=>Math.hypot(p.x-roomPoints[r.id].x,p.y-roomPoints[r.id].y)<65);if(close){e.preventDefault();setSpot(close.id);}}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 function clue(key:string,text:string){if(mediator||spectator)return;if(online){online.send({type:'clue',id:key});return;}updateTeam(s=>s.clues.includes(key)?s:{...s,clues:[...s.clues,key],notes:[...s.notes,text]});setMessage('Descoberta registrada no diário desta equipe.');setNotice(text);}
 function playRing(){if(!soundRef.current)return;try{const Constructor=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!Constructor)return;const context=audioRef.current||(audioRef.current=new Constructor());void context.resume().then(()=>ringPhone(context)).catch(()=>{});}catch{}}
 function saveMission(stage:number){if(mediator||t.stage<stage||stage===4&&!meeting||stage>=3&&t.eventDelivered&&!t.eventRead)return;const mission=caseData.missions[stage];if((mission.requires||[]).some(id=>!t.clues.includes(id)))return;const d=getDraft(stage);if(d.choice<0||d.choice>=mission.options.length||d.memo.trim().length<30)return;if(spectator)return;if(online){online.send({type:'decision',stage,choice:d.choice,memo:d.memo});return;}const option=mission.options[d.choice],decision={option:d.choice,plan:option.action,memo:d.memo.trim(),consequence:option.consequence};const deliver=stage===2&&!t.eventDelivered&&!ringed.current.has(teamId);if(deliver){ringed.current.add(teamId);playRing();}updateTeam(s=>commitDecision(s,stage,decision,caseData.event));setNotice(deliver?'A coordenação está ligando. Um novo comunicado aguarda você no celular da sala da coordenação. '+option.consequence:option.consequence);setMessage(deliver?`${actors[teamId].name}: nova ligação da coordenação. Consulte o celular no mapa.`:`${actors[teamId].name}: plano registrado. ${option.consequence}`);}
 function consult(stage:number){lastRoom.current=spot&&rooms.some(r=>r.id===spot)?spot:stageRooms[Math.min(t.stage,4)];setConsultTopic(stage);setSpot('consultant');}
 function openSource(e:Evidence,index:number){go(evidencePoint(teamId,e.id,e.room,index),`evidence:${e.id}`);}
 function getDraft(stage:number):Draft{const saved=t.decisions[stage];return drafts[`${teamId}-${stage}`]||{choice:saved?.option??-1,memo:saved?.memo||''};}
 function renderMission(stage:number){return <MissionEditor mission={caseData.missions[stage]} stage={stage} teamId={teamId} state={t} draft={getDraft(stage)} onDraft={d=>setDrafts(old=>({...old,[`${teamId}-${stage}`]:d}))} onSave={()=>saveMission(stage)} disabled={mediator||!!spectator} meeting={meeting} onVisit={id=>{setSpot(null);const r=rooms.find(r=>r.id===id)!;go(r,id);}} onConsult={()=>consult(stage)}/>;}
 function summon(){if(!ready)return;if(online){online.send({type:'summon'});return;}setMeeting(true);setPositions(starts.map((_,i)=>({x:675+(i%4)*45,y:480+Math.floor(i/4)*25})));route.current=[];arrival.current=null;setSpot(null);setMessage('As três equipes estão no auditório. Cada uma apresenta seu próprio plano; não há troca de recursos.');}
 function reset(){setTeams(freshTeams());setRemaining(GAME_SECONDS);setDeadline(null);setDebriefClosed(false);setPositions(starts.map(p=>({...p})));setActive(0);setInspect(0);setMeeting(false);setSpot(null);setDrafts({});setReviewDraft('');ringed.current.clear();receipts.current.clear();route.current=[];arrival.current=null;setMessage(firstMessage);}
 const missionRoom=rooms.find(r=>r.id===stageRooms[Math.min(t.stage,4)])!;
 return <div className="hp-shell" onPointerDown={()=>{if(!sound||audioRef.current)return;try{audioRef.current=new AudioContext();void audioRef.current.resume();}catch{}}}>
 <header className="hp-header"><a className="hp-brand" href="/"><span className="hp-cross">H</span><span>Plantão da Mudança<small>Hospital Horizonte · O protocolo é só o começo</small></span></a><div className="hp-preview"><span>{online?`SALA ${online.room}`:'PREVIEW INDIVIDUAL'}</span><small>{online?`${online.connected?'Conectado':'Reconectando'} · ${online.snapshot?.online||0}/40 participantes`:'Personagens controlados por você • sem conexão entre jogadores'}</small></div><div className="hp-header-actions"><button aria-pressed={sound} onClick={()=>setSound(v=>!v)} title={sound?'Desativar avisos sonoros':'Ativar avisos sonoros'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}<span>{sound?'Som ligado':'Som desligado'}</span></button><button onClick={()=>setSource(true)} title="Referenciais"><BookOpen size={19}/><span>Referenciais</span></button><button onClick={()=>setMenu(!menu)}><Users size={19}/><span>{online?.me.kind==='professor'?'Convites':'Papéis'}</span></button></div></header>
 {online?.error&&<div className="hp-online-error" role="alert"><span>{online.error}</span><button onClick={online.clearError}>Fechar aviso</button></div>}
 <section className="hp-session-bar" aria-label="Tempo do jogo"><div className={`hp-timer ${remaining===0?'expired':remaining<=300?'ending':''}`}><Timer size={23}/><strong>{timerLabel(remaining)}</strong><span>{remaining===0?'Tempo da atividade encerrado · sigam para a discussão':deadline!==null?'Jogo em andamento':remaining===GAME_SECONDS?'30 minutos · aguardando início':'Cronômetro pausado'}</span></div>{mediator&&<button className="hp-timer-control" disabled={remaining===0||debriefClosed} onClick={toggleTimer}>{deadline!==null?<Pause size={17}/>:<Play size={17}/>} {deadline!==null?'Pausar':remaining===GAME_SECONDS?'Iniciar jogo':'Continuar'}</button>}{debriefClosed&&<button className="hp-study-button" onClick={()=>setSpot('delivery')}><Download size={18}/> Meu resumo de estudo</button>}</section>
 <section className="hp-briefing"><div className="hp-briefing-problem"><span className="hp-overline">PAINEL DA MISSÃO · DADOS E PERSONAGENS FICTÍCIOS</span><h2>Um protocolo publicado. Três problemas de implementação.</h2><p>{institutionalProblem}</p></div>{!mediator&&<article className="hp-private-objectives" style={{'--actor':actors[teamId].color} as React.CSSProperties}><span>MISSÃO DA {actors[teamId].name.toUpperCase()}</span><h3>{caseData.title}</h3><ul>{caseData.objectives.map(o=><li key={o}>{o}</li>)}</ul></article>}</section>
 <main className="hp-workspace"><section className="hp-world">
 <div className="hp-world-heading"><div><span className="hp-overline">MISSÃO DE IMPLEMENTAÇÃO</span><h1>{meeting?'Encontro institucional':'Explorem. Escutem. Transformem a rotina.'}</h1></div><span className="hp-status">{meeting?'Auditório aberto':'3 equipes independentes'}</span></div>
 <div className="hp-map" ref={mapRef} tabIndex={0} aria-label={spectator?'Mapa compartilhado. Você acompanha os personagens e pode consultar os ambientes.':'Hospital navegável. Clique no piso ou use as setas. E interage com uma sala próxima.'} onClick={e=>{const b=e.currentTarget.getBoundingClientRect();go({x:(e.clientX-b.left)/b.width*900,y:(e.clientY-b.top)/b.height*600});}}>
 <img className="hp-floor" src="/hospital-preview/hospital-map.png" alt="Hospital em pixel art com coordenação, posto de enfermagem, almoxarifado, sala da equipe, núcleo de qualidade e auditório" draggable={false}/>
 {rooms.map(r=><div key={r.id} className="hp-room-label" style={{left:`${r.x/9}%`,top:`${(r.y<300?32:553)/6}%`}}><strong>{r.name}</strong><small>{r.tag}</small></div>)}
 {rooms.map((r,i)=>{const point=roomPoints[r.id];return <button key={r.id} className={`hp-hotspot ${!mediator&&r.id===missionRoom.id&&!t.complete?'hp-target':''} ${stageRooms.includes(r.id)&&t.stage>stageRooms.indexOf(r.id)?'hp-complete':''}`} style={{left:`${point.x/9}%`,top:`${point.y/6}%`}} onClick={e=>{e.stopPropagation();go(point,r.id);}} aria-label={`Ir até ${r.name} e interagir`}><span>{stageRooms.includes(r.id)&&t.stage>stageRooms.indexOf(r.id)?<Check size={18}/>:i===1||i===3?<MessageCircle size={18}/>:r.id==='final'?<Users size={18}/>:<ClipboardList size={18}/>}</span></button>;})}
 {ambientPeople.map(person=>{const p=ambientPosition(person,ambientTime);return <div key={person.id} className="hp-ambient is-walking" style={{left:`${p.x/9}%`,top:`${p.y/6}%`}} aria-hidden="true"><Sprite index={person.sprite}/></div>;})}
 {caseData.evidence.map((e,i)=>{const p=evidencePoint(teamId,e.id,e.room,i);return <button key={e.id} className={`hp-evidence-map ${e.mode==='document'?'is-document':''} ${t.clues.includes(e.id)?'discovered':''}`} style={{left:`${p.x/9}%`,top:`${p.y/6}%`}} onClick={ev=>{ev.stopPropagation();openSource(e,i);}} aria-label={`${e.mode==='document'?'Ler':'Conversar com'} ${e.person}`}><span className="hp-evidence-symbol">{e.mode==='document'?<FileText size={20}/>:<MessageCircle size={18}/>}</span>{e.mode==='person'&&<Sprite index={[0,1,5][i]}/>}<small>{e.mode==='document'?'Documento':e.person.split(' ').slice(-1)[0]}</small></button>;})}
 <button className="hp-consultant-map" style={{left:'63.3%',top:'48%'}} onClick={e=>{e.stopPropagation();lastRoom.current=stageRooms[Math.min(t.stage,4)];setConsultTopic(Math.min(t.stage,4));go({x:570,y:285},'consultant');}} aria-label="Conversar com a consultora Iris"><img src="/hospital-preview/consultant.png" alt=""/><span>Iris · consultora</span></button>
 {t.eventDelivered&&<button className={`hp-phone-map ${!t.eventRead?'ringing':''}`} style={{left:'24%',top:'20%'}} onClick={e=>{e.stopPropagation();go({x:210,y:120},'phone');}} aria-label={`Celular da coordenação: ${t.eventRead?'reler comunicado':'novo comunicado'}`}><Smartphone size={23}/><span>{t.eventRead?'Comunicado':'Nova ligação'}</span></button>}
 {positions.map((p,i)=><div key={i} className={`hp-avatar ${active===i?'is-active':''} ${active===i&&route.current.length?'is-walking':''}`} style={{left:`${p.x/9}%`,top:`${p.y/6}%`,'--actor':actors[i].color} as React.CSSProperties}><span className="hp-avatar-name">{actors[i].name}</span><Sprite index={i}/><span className="hp-avatar-ring"/></div>)}
 <span className="hp-corridor-label">CORREDOR PRINCIPAL</span>
 </div>
 <div className="hp-world-bottom"><p><MapPin size={17}/><span>{spectator?'Clique nas fontes para acompanhar · decisões pelo representante':'Clique para caminhar · setas / WASD · E para interagir'}</span></p><button onClick={()=>setJournal(true)}><ClipboardList size={17}/> Diário da equipe</button></div>
 {t.eventDelivered&&!t.eventRead&&<button className="hp-incoming-call" onClick={()=>go({x:210,y:120},'phone')}><Smartphone size={20}/><span>Nova ligação para {actors[teamId].name}. Vá à coordenação para ler o comunicado.</span></button>}<div className="hp-message" role="status"><MessageCircle size={20}/><p>{message}</p></div>
 <div className="hp-mobile-pad" aria-label="Controle de movimento"><button onClick={()=>move(-1,0)} aria-label="Esquerda"><ArrowLeft/></button><button onClick={()=>move(0,-1)} aria-label="Cima"><ArrowUp/></button><button onClick={()=>move(0,1)} aria-label="Baixo"><ArrowDown/></button><button onClick={()=>move(1,0)} aria-label="Direita"><ArrowRight/></button></div>
 {mediator&&<FacultyBoard teams={teams} onInspect={setInspect} onJournal={i=>{setInspect(i);setJournal(true);}}/>}
 </section>
 <aside className="hp-side"><section className="hp-control"><span className="hp-overline">{spectator?'VOCÊ ACOMPANHA':'VOCÊ CONTROLA'}</span>{!online&&<NativeSelect value={active} onChange={e=>{setActive(Number(e.target.value));setSpot(null);setMenu(false);setMessage(Number(e.target.value)>=3?'Você pode visitar qualquer sala e acompanhar as três equipes.':firstMessage);}} aria-label="Escolher personagem do preview">{actors.map(a=><option key={a.id} value={a.id}>{a.name}{a.id>=3?' · acesso livre':''}</option>)}</NativeSelect>}<div className="hp-person"><span style={{background:actors[active].color}}/><div><strong>{actors[active].name}</strong><small>{mediator?actors[active].unit:spectator?'Participante · decisões pelo representante':'Representante da equipe'}</small></div></div>{mediator&&<label className="hp-inspect">Acompanhar o diário de<NativeSelect value={inspect} onChange={e=>{setInspect(Number(e.target.value));}}>{actors.slice(0,3).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</NativeSelect></label>}</section>
 <button className="hp-side-consultant" onClick={()=>consult(Math.min(t.stage,4))}><img src="/hospital-preview/consultant.png" alt=""/><span>Consultar Iris<small>Conceitos e exemplos do referencial</small></span></button><section className="hp-mission"><span className="hp-overline">{mediator?'ACOMPANHAMENTO':'MISSÃO DA SUA EQUIPE'}</span><h2>{t.complete?'Plano apresentado':caseData.missions[Math.min(t.stage,4)].title}</h2><p>{t.complete?'A equipe concluiu sua apresentação. O professor pode conduzir a reflexão final.':t.stage===4?'Preparem um indicador de incorporação. O encontro começa quando as três equipes estiverem prontas.':caseData.problem}</p><ol>{missionNames.map((name,i)=><li className={i<t.stage||t.complete?'done':i===t.stage?'current':''} key={name}><span>{i<t.stage||t.complete?<Check size={13}/>:i+1}</span>{caseData.missions[i].title}</li>)}</ol>{!t.complete&&<button className="hp-primary" onClick={()=>go(roomPoints[missionRoom.id],missionRoom.id)}><DoorOpen size={17}/> Visitar {missionRoom.name}</button>}</section>
 <section className="hp-roster"><span className="hp-overline">NO HOSPITAL</span>{actors.map((a,i)=><button key={i} disabled={!!online} onClick={()=>{setActive(i);setSpot(null);}}><span style={{background:a.color}}/><strong>{a.name}</strong><small>{i<3?`${teams[i].complete?5:teams[i].stage}/5 etapas`:'Acesso livre'}</small></button>)}</section>
 {mediator&&<section className="hp-host"><a className="hp-board-jump" href="#acompanhamento">Ver decisões das equipes</a><span className="hp-overline">MEDIAÇÃO</span><p>Comunicados chegam automaticamente ao fim da terceira missão de cada equipe.</p><button disabled={!ready||meeting} className="hp-primary" onClick={summon}>Convocar as 3 equipes</button><small>{ready?'As três equipes podem se reunir.':'Disponível após as quatro etapas iniciais de cada equipe.'}</small>{meeting&&<button className="hp-primary" disabled={!finished||debriefClosed} onClick={conclude}>{debriefClosed?'Resumos entregues':'Encerrar discussão e entregar resumos'}</button>}</section>}
 {spectator&&<div className="hp-spectator-note">Acompanhe os relatos e o diário de sua equipe. Discutam pelo Meet; seu representante registra o plano.</div>}{!online&&<button className="hp-reset" onClick={reset}><RotateCcw size={15}/> Reiniciar preview</button>}<button className="hp-reset" onClick={onLeave}>Sair da partida</button>
 </aside></main>
 <footer className="hp-footer"><span>Hospital fictício · nenhuma informação de pacientes reais</span><span>{online?'Partida compartilhada · áudio pelo Google Meet':'Exploração individual'}</span></footer>
 <Dialog open={!!spot} onOpenChange={v=>{if(!v)setSpot(null);}}><DialogContent className="hp-dialog"><DialogTitle>{spot==='delivery'?'Iris entrega seu resumo de estudo':spot==='consultant'?'Consultoria com Iris':spot==='phone'?'Comunicado da coordenação':evidence?.person||currentRoom?.name}</DialogTitle><DialogDescription>{spot==='delivery'?'Após a discussão final':spot==='consultant'?'Conceitos e exemplos':spot==='phone'?'Acontecimento da missão':evidence?.role||currentRoom?.tag} · {mediator?`Você acompanha ${actors[teamId].name}`:actors[active].name}</DialogDescription>
 {mediator&&spot!=='final'&&spot!=='consultant'&&spot!=='delivery'&&<div className="hp-info">Acesso de mediação: consulte as descobertas e converse com a equipe pelo Meet. As decisões pertencem aos representantes.</div>}
 {spot==='delivery'&&debriefClosed&&<div className="hp-study-delivery"><div className="hp-consultant-intro"><img src="/hospital-preview/consultant.png" alt="Iris, consultora de implementação"/><div><span className="hp-overline">IRIS · DEPOIS DA NOSSA DISCUSSÃO</span><h3>Leve as perguntas com você.</h3><p>“Vocês investigaram o contexto, fizeram escolhas e discutiram suas limitações. Preparei um resumo para retomar os conceitos e o caso da {actors[teamId].name}. Cada integrante pode baixar sua própria cópia para estudar.”</p></div></div><p>O PDF reúne os cinco referenciais, exemplos da missão, dados simulados, armadilhas conceituais, perguntas de revisão e textos-base com links. É um guia de estudo; não atribui uma nota às decisões da equipe.</p><a className="hp-primary" href={studyFiles[teamId]} download><Download size={18}/> Baixar resumo · {actors[teamId].name} · PDF</a><p className="hp-study-prompt">“Ao reler, pergunte: qual determinante sustentou a estratégia e que medida mostraria se a prática foi incorporada?” — Iris</p>{t.review&&<div className="hp-faculty-review"><h3>Devolutiva para retomar no estudo</h3><p>{t.review}</p></div>}</div>}
 {spot==='consultant'&&<Consultant topic={consultTopic} onTopic={setConsultTopic} teamId={teamId} onReturn={()=>setSpot(lastRoom.current)}/>}
 {spot==='phone'&&<><div className="hp-phone-message"><Smartphone size={29}/><span>PARA {actors[teamId].name.toUpperCase()} · APÓS A TERCEIRA MISSÃO</span><h3>O contexto mudou. Como o plano responde?</h3><p>{t.event||'Ainda não há comunicado para esta equipe.'}</p></div>{t.eventDelivered&&<><div className="hp-info">Revisitem a terceira missão se necessário. Na próxima decisão, expliquem o que muda, o que permanece e o que precisa ser acompanhado.</div><button className="hp-primary" disabled={mediator||!!spectator} onClick={()=>{if(online){online.send({type:'read-event'});return;}updateTeam(s=>({...s,eventRead:true}));setNotice('Leitura registrada. O comunicado permanece disponível no celular da coordenação.');}}>Confirmar leitura do comunicado</button><button className="hp-text-button" onClick={()=>setSpot('facilitation')}>Revisar o plano de facilitação</button></>}</>}
 {t.eventRead&&rooms.some(r=>r.id===spot)&&<div className="hp-event"><Flag size={18}/>{t.event}</div>}
 {spot==='kta'&&<><div className="hp-document"><span>DOSSIÊ DA UNIDADE · {actors[teamId].unit}</span><h3>{caseData.title}</h3><p>{caseData.problem}</p></div><div className="hp-data-grid">{caseData.data.map(d=><article key={d.label}><span>{d.label}</span><strong>{d.value}</strong><p>{d.meaning}</p></article>)}</div>{renderMission(0)}</>}
 {evidence&&<EvidenceCard evidence={evidence} discovered={t.clues.includes(evidence.id)} disabled={mediator||!!spectator} onRecord={()=>clue(evidence.id,`${evidence.person}: ${evidence.finding}`)}/>}
 {rooms.some(r=>r.id===spot)&&caseData.evidence.some(e=>e.room===spot)&&<section className="hp-room-sources"><h3>Fontes disponíveis neste ambiente</h3>{caseData.evidence.filter(e=>e.room===spot).map(e=><EvidenceCard key={e.id} evidence={e} discovered={t.clues.includes(e.id)} disabled={mediator||!!spectator} onRecord={()=>clue(e.id,`${e.person}: ${e.finding}`)}/>)}</section>}
 {spot==='cfir'&&renderMission(1)}
 {spot==='staff'&&<div className="hp-info">Confrontem os relatos e documentos com as outras fontes. O diagnóstico será pactuado no posto de enfermagem.</div>}
 {spot==='facilitation'&&renderMission(2)}
 {spot==='reaim'&&renderMission(3)}
 {spot==='final'&&<>{!meeting?<><div className="hp-document"><span>REUNIÃO INSTITUCIONAL</span><p>As equipes apresentam problemas e planos diferentes. Cada uma precisa defender a relação entre suas evidências, estratégias e medidas de implementação, sem transferir descobertas ou recursos.</p></div><div className="hp-readiness">{teams.map((s,i)=><p key={i}><span style={{background:actors[i].color}}/>{actors[i].name}<strong>{s.stage>=4?'Pronta para a reunião':`${s.stage}/4 etapas iniciais`}</strong></p>)}</div>{mediator?<button className="hp-primary" disabled={!ready} onClick={summon}>Convocar as três equipes ao auditório</button>:<p className="hp-info">Quando todas estiverem prontas, alterne para Professor ou Seminário e convoque o encontro.</p>}</>:<>{renderMission(4)}<div className="hp-reflection"><h3>{finished?'Três planos para discutir':'Roteiro de discussão desta equipe'}</h3><ul>{caseData.review.map(q=><li key={q}>{q}</li>)}</ul><p>Apresentem a escolha, suas limitações e o que faria a equipe revisar o plano. O encontro não transforma as três soluções em uma receita universal.</p>{mediator&&finished&&<button className="hp-primary" disabled={debriefClosed} onClick={conclude}>{debriefClosed?'Discussão encerrada · resumos disponíveis':'Encerrar discussão e chamar Iris'}</button>}{debriefClosed&&<button className="hp-primary" onClick={()=>setSpot('delivery')}>Receber meu resumo de estudo</button>}</div>{mediator&&<div className="hp-memo"><h4>Devolutiva para {actors[teamId].name}</h4><label htmlFor="faculty-review">Comentem a coerência do plano ou proponham uma revisão específica.</label><textarea id="faculty-review" value={reviewDraft} onChange={e=>setReviewDraft(e.target.value)} maxLength={1500} rows={4}/><button className="hp-primary" onClick={()=>{if(online){online.send({type:'review',team:teamId,text:reviewDraft.trim()});return;}updateTeam(s=>({...s,review:reviewDraft.trim()}));setNotice('Devolutiva registrada no diário desta equipe.');}}>Registrar devolutiva</button></div>}</>}</>}
 {notice&&<div className="hp-notice" role="status"><MessageCircle size={18}/><p>{notice}</p></div>}<button className="hp-text-button" onClick={()=>setSpot(null)}><DoorOpen size={16}/> Voltar ao hospital</button>
 </DialogContent></Dialog>
 <Dialog open={journal} onOpenChange={setJournal}><DialogContent className="hp-dialog"><DialogTitle>Diário · {actors[teamId].name}</DialogTitle><DialogDescription>{actors[teamId].unit} · descobertas próprias, sem trocas entre equipes</DialogDescription><div className="hp-journal">{t.decisions.length>0&&<><h3>Plano em construção</h3>{t.decisions.map((d,i)=><article key={i}><span>{i+1}</span><div><h4>{caseData.missions[i].title}</h4><p>{d.plan}</p><strong>Justificativa da equipe</strong><p>{d.memo}</p><strong>Consequência a acompanhar</strong><p>{d.consequence}</p></div></article>)}</>}{t.review&&<div className="hp-faculty-review"><h3>Devolutiva do professor / seminário</h3><p>{t.review}</p></div>}<h3>Descobertas e consequências</h3>{t.notes.length?t.notes.map((n,i)=><p key={i}>{n}</p>):<p>Visitem os setores e conversem com os profissionais para registrar as primeiras descobertas.</p>}</div></DialogContent></Dialog>
 <Dialog open={source} onOpenChange={setSource}><DialogContent className="hp-dialog"><DialogTitle>Referenciais da missão</DialogTitle><DialogDescription>Simulação educacional fictícia. Não é um instrumento validado de avaliação.</DialogDescription><div className="hp-references">{references.map(r=><a href={r.url} key={r.url} target="_blank" rel="noreferrer"><strong>{r.short}</strong><span>{r.title}</span></a>)}<p>O cenário e a aplicação foram elaborados com auxílio de inteligência artificial. A discussão e a avaliação acadêmica permanecem com os docentes e discentes.</p></div></DialogContent></Dialog>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="hp-dialog"><DialogTitle>{online?.me.kind==='professor'?'Convites da partida':'Papéis no hospital'}</DialogTitle><DialogDescription>{online?'Cada convite define o papel e a equipe nesta partida.':'Neste preview, você alterna personagens para testar o percurso.'}</DialogDescription>{online?.snapshot?.invites&&<InvitationList invites={online.snapshot.invites} room={online.room}/>}<div className="hp-journal"><p><strong>Três representantes:</strong> investigam, decidem e apresentam os planos de suas próprias equipes. Não compartilham itens ou descobertas pelo jogo.</p><p><strong>Professor:</strong> visita todas as salas, acompanha os diários e conduz a reflexão.</p><p><strong>Grupo do seminário:</strong> seis apresentadores têm avatares próprios e acesso livre, acompanham os comunicados automáticos e registram devolutivas.</p><p>A reunião final reúne as equipes no auditório para apresentar e discutir, sem transferir recursos. O áudio continua no Google Meet.</p></div></DialogContent></Dialog>
 </div>;
}
