import {tr} from './i18n';
import {hospitalAssets} from './lib/hospital-assets';
'use client';
import {BookOpen,MessageCircle,Smartphone} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {frameworkTopics} from '@/lib/hospital-consultant';
import {actors,type TeamState} from '@/lib/hospital-preview';
import {cases} from '@/lib/hospital-missions';
export function Consultant({topic,onTopic,teamId,onReturn}:{topic:number;onTopic:(v:number)=>void;teamId:number;onReturn:()=>void}){return <div className="hp-consultation"><div className="hp-consultant-intro"><img src={hospitalAssets.consultant} alt={tr("Iris, consultora de implementação em pixel art")}/><div><span className="hp-overline">{tr("IRIS · CONSULTORIA DE IMPLEMENTAÇÃO")}</span><h3>{tr("Vamos ligar o conceito ao seu caso?")}</h3><p>{tr("Escolha um referencial. Eu explico a ideia, mostro uma aplicação à sua missão e indico onde encontrá-la no texto-base.")}</p></div></div><Tabs value={String(topic)} onValueChange={v=>onTopic(Number(v))}><TabsList className="hp-topic-tabs">{tr(['KTA','CFIR','PARIHS/i-PARIHS','RE-AIM','Desfechos'].map((name,i)=><TabsTrigger key={name} value={String(i)}>{tr(name)}</TabsTrigger>))}</TabsList>{tr(frameworkTopics.map((f,i)=><TabsContent key={f.name} value={String(i)}><div className="hp-consultant-explanation"><h3>{tr(f.question)}</h3><p>{tr(f.explanation)}</p></div><dl className="hp-concept-list">{tr(f.concepts.map(c=><div key={c.label}><dt>{tr(c.label)}</dt><dd>{tr(c.meaning)}</dd></div>))}</dl><div className="hp-example"><strong>{tr("No caso da ")}{tr(actors[teamId].name)}</strong><p>{tr(f.examples[teamId])}</p></div><div className="hp-pitfall"><strong>{tr("Armadilha conceitual")}</strong><p>{tr(f.pitfall)}</p></div><div className="hp-source-basis"><BookOpen size={18}/><div><strong>{tr("Onde encontrar no referencial")}</strong>{tr(f.source.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{tr(s.label)}<span>{tr(s.where)}</span></a>))}</div></div></TabsContent>))}</Tabs><button className="hp-primary" onClick={onReturn}>{tr("Retomar a missão")}</button></div>;}
export function FacultyBoard({teams,onInspect,onJournal}:{teams:TeamState[];onInspect:(i:number)=>void;onJournal:(i:number)=>void}){return <section id="acompanhamento" className="hp-faculty-board"><div className="hp-faculty-heading"><div><span className="hp-overline">{tr("PROFESSOR E SEMINÁRIO · ACOMPANHAMENTO")}</span><h2>{tr("Decisões das equipes e fundamentos para discutir")}</h2><p>{tr("O referencial sustenta a leitura conceitual. A relação com cada plano é uma aplicação didática ao caso fictício; a coerência da justificativa deve ser discutida.")}</p></div><MessageCircle size={27}/></div><div className="hp-faculty-columns">{teams.map((t,i)=><article key={i} style={{'--actor':actors[i].color} as React.CSSProperties}><header><button onClick={()=>onInspect(i)}>{tr(actors[i].name)}</button><span>{tr(t.stage)}{tr("/5 missões")}</span></header>{tr(t.eventDelivered&&<div className="hp-faculty-event"><Smartphone size={15}/><span>{tr(t.eventRead?'Comunicado lido':'Comunicado aguardando leitura')}</span></div>)}<div className="hp-decision-summaries">{tr(frameworkTopics.map((f,j)=>{const d=t.decisions[j];return <section key={f.name}><h3>{tr(j+1)}{tr(". ")}{tr(f.name)}</h3>{tr(d?<><strong className="hp-choice-summary">{tr(cases[i].missions[j].options[d.option].title)}</strong><p>{tr(d.plan)}</p><blockquote><span>{tr("Trecho da justificativa")}</span>{d.memo.length>180?d.memo.slice(0,180)+'…':d.memo}</blockquote></>:<p className="hp-not-recorded">{tr("Decisão ainda não registrada.")}</p>)}<div className="hp-bibliographic-basis"><strong>{tr("Fundamento conceitual")}</strong><p>{tr(f.basis)}</p>{tr(f.source.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{tr(s.label)} {tr(" · ")}{tr(s.where)}</a>))}</div></section>;}))}</div><button className="hp-primary" onClick={()=>onJournal(i)}>{tr("Ler plano e justificativas completas")}</button>{t.review&&<p className="hp-board-review"><strong>{tr("Devolutiva registrada:")}</strong> {t.review}</p>}</article>)}</div></section>;}
