import {createRoot} from 'react-dom/client';
import {useState} from 'react';
import HospitalGame from './HospitalGame';
import {useRoom,type Login} from './room-client';
import type {Person} from '../worker/session';
import './base.css';
import './lobby.css';
function saved():Login|null{const invite=new URLSearchParams(location.hash.slice(1));if(invite.get('room')&&invite.get('invite'))return null;try{const value=JSON.parse(sessionStorage.getItem('plantao-session')||'null');return value&&typeof value.room==='string'&&typeof value.token==='string'&&value.me?value:null;}catch{return null;}}
function App(){const [login,setLogin]=useState<Login|null>(saved),[preview,setPreview]=useState(false),[mode,setMode]=useState<'join'|'create'>('join'),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const hash=new URLSearchParams(location.hash.slice(1));const [room,setRoom]=useState(hash.get('room')||''),[invite,setInvite]=useState(hash.get('invite')||'');const online=useRoom(login);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await fetch(mode==='create'?'/api/rooms':`/api/rooms/${room.toUpperCase()}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='create'?{key}:{invite})});const data=await response.json() as {error?:string;room:string;token:string;me:Person};if(!response.ok)throw new Error(data.error||'Não foi possível entrar.');const value={room:mode==='create'?data.room:room.toUpperCase(),token:data.token,me:data.me};sessionStorage.setItem('plantao-session',JSON.stringify(value));history.replaceState(null,'',location.pathname);setLogin(value);setKey('');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 function leave(){sessionStorage.removeItem('plantao-session');setLogin(null);setPreview(false);}
 if(preview||online?.snapshot)return <HospitalGame online={online} onLeave={leave}/>;
 if(online)return <main className="pl-lobby"><h1>Retomando o plantão…</h1><p>{online.error||'Conectando à partida compartilhada.'}</p><button onClick={leave}>Voltar à entrada</button></main>;
 return <main className="pl-lobby"><div className="pl-title"><span>HOSPITAL HORIZONTE</span><h1>Plantão<br/>da Mudança</h1><p>O protocolo é só o começo.</p></div><section className="pl-entry"><div className="pl-entry-tabs"><button aria-pressed={mode==='join'} onClick={()=>setMode('join')}>Entrar na partida</button><button aria-pressed={mode==='create'} onClick={()=>setMode('create')}>Criar partida</button></div><h2>{mode==='join'?'Seu convite para o plantão':'Preparar o seminário'}</h2><p>{mode==='join'?'Use o convite enviado pela organização. Seu papel e sua equipe já estão definidos no link.':'Crie uma sala e distribua os convites aos três representantes, aos demais alunos, ao professor e aos seis apresentadores.'}</p><form onSubmit={submit}>{mode==='join'?<><label htmlFor="room">Código da partida</label><input id="room" value={room} onChange={e=>setRoom(e.target.value.toUpperCase())} minLength={10} maxLength={10} required autoComplete="off"/><label htmlFor="invite">Código do convite</label><input id="invite" value={invite} onChange={e=>setInvite(e.target.value.trim())} maxLength={64} required autoComplete="off"/></>:<><label htmlFor="setup">Chave da organização</label><input id="setup" type="password" value={key} onChange={e=>setKey(e.target.value)} required autoComplete="off"/><small>Chave definida pela organização para criar partidas.</small></>}<button className="hp-primary" disabled={busy}>{busy?'Conectando…':mode==='join'?'Entrar no hospital':'Criar sala e receber convites'}</button></form>{error&&<p className="pl-error" role="alert">{error}</p>}<button className="pl-preview" onClick={()=>setPreview(true)}>Explorar o preview individual</button></section><div className="pl-format"><strong>40 participantes · 3 equipes de 11</strong><p>Três representantes, professor e seis apresentadores navegam pelo hospital. Os outros 30 alunos acompanham suas equipes e discutem pelo Google Meet. As descobertas e decisões de cada equipe permanecem separadas.</p><small>Simulação educacional fictícia · desenvolvida com auxílio de inteligência artificial.</small></div></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
