import {useEffect,useRef,useState} from 'react';
import type {RoomData,Person,Invitation,Command} from '../worker/session';
import type {Point,TeamState} from './lib/hospital-preview';
export type Login={room:string;token:string;me:Person};
export type Snapshot={teams:TeamState[];positions:Point[];meeting:boolean;released:boolean;timer:RoomData['timer'];revision:number;online:number;serverNow:number;invites?:Invitation[]};
export function useRoom(login:Login|null){const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[positions,setPositions]=useState<Point[]>([]),[connected,setConnected]=useState(false),[error,setError]=useState('');const socket=useRef<WebSocket|null>(null),offset=useRef(0);
 useEffect(()=>{if(!login)return;let stopped=false,retry=0,timer:ReturnType<typeof setTimeout>;function connect(){if(stopped)return;const ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/api/rooms/${login!.room}/ws`);socket.current=ws;ws.onopen=()=>ws.send(JSON.stringify({type:'auth',token:login!.token}));ws.onmessage=e=>{try{const message=JSON.parse(e.data);if(message.type==='snapshot'){setSnapshot(message.data);setPositions(message.data.positions);offset.current=message.data.serverNow-Date.now();setConnected(true);setError('');retry=0;}else if(message.type==='move')setPositions(old=>old.map((p,i)=>i===message.actor?message.point:p));else if(message.type==='error')setError(message.error);}catch{setError('Não foi possível ler a atualização da partida.');}};ws.onclose=e=>{setConnected(false);if(stopped)return;if(e.code===1008||e.code===1000){setError(e.reason||'Esta sessão foi encerrada. Entre novamente pelo convite.');return;}setError('Conexão interrompida. Tentando retomar a partida…');timer=setTimeout(connect,Math.min(1000*2**retry++,10000));};ws.onerror=()=>setError('Não foi possível conectar. Confira sua conexão.');}connect();return()=>{stopped=true;clearTimeout(timer);socket.current?.close();socket.current=null;};},[login]);
 function send(cmd:Command){if(socket.current?.readyState!==WebSocket.OPEN||!connected){setError('Aguarde a conexão para registrar a ação.');return false;}socket.current.send(JSON.stringify(cmd));return true;}
 return login?{...login,snapshot,positions,connected,error,offset:offset.current,send,clearError:()=>setError('')}:null;
}
export type OnlineRoom=NonNullable<ReturnType<typeof useRoom>>;
export function InvitationList({invites,room}:{invites:Invitation[];room:string}){const [copied,setCopied]=useState('');function url(code:string){return `${location.origin}/#room=${room}&invite=${code}`;}return <div className="hp-invites"><p>Compartilhe cada link com o papel indicado. O convite de representante controla o avatar; o convite de acompanhamento permite dez alunos da equipe. O professor e os seis apresentadores têm acesso de mediação.</p>{invites.map(i=><article key={i.code}><strong>{i.label}</strong><input aria-label={`Link de ${i.label}`} readOnly value={url(i.code)} onFocus={e=>e.target.select()}/><button onClick={()=>{void navigator.clipboard.writeText(url(i.code)).then(()=>setCopied(i.code)).catch(()=>setCopied('Selecione e copie o link acima.'));}}>{copied===i.code?'Copiado':'Copiar convite'}</button></article>)}{copied==='Selecione e copie o link acima.'&&<p role="status">{copied}</p>}</div>;}
